update Dialyxir version to 1.1.0
etalab/transport-site pull request #1516
Opened 2021-02-19 10:35 UTC by fchabouis

Pour info @thbar une nouvelle [release](https://github.com/jeremyjh/dialyxir/releases) de https://github.com/jeremyjh/dialyxir/releases a été faite il y a 16 heures et je n'arrivais plus à lancer mon serveur en local.

2021-02-19 10:43 UTC, thbar requested changes
C'est curieux que ça ne fonctionne plus en local effectivement !

Merci d'avoir lancé le sujet, il y a 2 modifications à faire et ça sera bon pour moi.

2021-02-19 10:43 UTC, thbar commented on mix.exs
> +      {:dialyxir, "~> 1.1.0", only: :dev, runtime: false, git: "https://github.com/jeremyjh/dialyxir.git"},
J'utilisais la version 1.0.0 mais via `master`, en attendant qu'une version officielle soit publiée. Du coup il vaut mieux enlever l'option `git:` pour installer depuis [hex.pm](https://hex.pm/packages/dialyxir).

Par ailleurs on peut supprimer la NOTE au dessus, qui était là pour penser à faire ça, mais pas très claire :-)

2021-02-19 16:11 UTC, fchabouis commented on mix.exs
> +      {:dialyxir, "~> 1.1.0", only: :dev, runtime: false, git: "https://github.com/jeremyjh/dialyxir.git"},
Merci pour les détails de l'histoire :)

2021-02-19 17:47 UTC, thbar requested changes

2021-02-19 17:47 UTC, thbar commented on mix.lock
> +  "dialyxir": {:git, "https://github.com/jeremyjh/dialyxir.git", "39a765467e858ad8e897918caefdadd7199a7f66", []},
@fchabouis il doit manquer je pense un `mix deps.update dialyxir` ici !

2021-02-22 08:28 UTC, merged

2021-02-22 08:28 UTC, thbar commented
Merci !