Mettre le nom du producteur de la donnée sur la page des datasets
etalab/transport-site pull request #1576
Opened 2021-03-31 12:51 UTC by fchabouis

close #1554 

![image](https://user-images.githubusercontent.com/15341118/113146952-9329ae80-9230-11eb-81a9-dc23dff32eb7.png)

2021-03-31 15:05 UTC, thbar requested changes
Un petit changement sur la traduction, le reste c'est plutôt des questionnements sans importance critique.

2021-03-31 15:05 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/details.html.eex
> +      <span class="dataset-metas-info-title">Producteur de la donnée</span>
Est-ce qu'il faut une traduction pour "Producteur de la donnée" ? J'imagine que oui ?

2021-03-31 15:05 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/_licence.html.eex
> +   	&#32<%= dgettext("page-dataset-details", "and ") %>
Je me suis demandé si on aurait pu faire autrement pour le `&#32` (mais c'est pas important a priori).

2021-03-31 15:05 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/details.html.eex
> +        <b><%= @dataset.organization %></b>
Y-a-t-il des cas où ce champ est potentiellement vide ? (je n'ai pas été voir). Si oui il faudrait peut-être mettre un if autour (mais à discuter, aucune idée).

2021-03-31 15:05 UTC, thbar commented on apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
> +msgstr "Type de données"
Il y a une majuscule en français, et pas en anglais du coup ?

2021-04-01 15:31 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/dataset/_licence.html.eex
> +   	&#32<%= dgettext("page-dataset-details", "and ") %>
je ne sais pas...j'aurais pu le mettre dans le dgettext mais c'est pas beaucoup mieux

2021-04-01 15:32 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/dataset/details.html.eex
> +        <b><%= @dataset.organization %></b>
Pour l'instant on ne fait pas de check non plus sur les autres champs (mauvais argument)
Et là j'ai un peu la flemme d'en mettre partout (encore pire argument !)

2021-04-01 15:37 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/details.html.eex
> +        <b><%= @dataset.organization %></b>
Oui mais ça explique le truc quand même, ça ira bien. Merci !

2021-04-01 15:37 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/_licence.html.eex
> +   	&#32<%= dgettext("page-dataset-details", "and ") %>
Ah non ça me va là, c'était juste par curiosité

2021-04-01 15:41 UTC, thbar approved these changes

2021-04-01 15:41 UTC, merged