Fix stream hasher
etalab/transport-site pull request #1624
Opened 2021-05-05 16:55 UTC by fchabouis

Je ne sais pas si on veut merger tout de suite, parce que le code en question n'est pas testé. C'est à discuter.

En regardant dans les logs des erreurs d'import, je suis tombé sur le cas [marseillais](https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone/).

Je ne sais pas à quel point il est fréquent, mais c'est peut-être pas si rare que ça :
* l'url de la ressource est en http, ce qui fait que la réponse est une 301, qui redirige vers la version https. Or pour le moment, si on a une réponse différente de 200, on ne calcule pas de hash.
* Mint n'accepte que des url encodées, or dans la ressource marseillaise, il y a des "|", ce qui fait échouer la méthode `fetch_status_and_hash`

2021-05-08 08:40 UTC, thbar requested changes
Le changement de logique sur le status doit pour avoir une bonne qualité être amélioré.

Voilà ce que j'avais en tête avant cette PR pour la suite:
- pour un status 200 uniquement, on accepte le résultat
- pour un status 301 ou 302, il faut suivre le redirect (faire une boucle récursive), avec une limite (exemple: 10 redirects) pour éviter les redirects infinis qui peuvent apparaître
- pour tout autre code, on lève une erreur

Finch ne supporte pas directement une option "follow redirect", il faudra l'implémenter chez nous, ce qui n'est pas très compliqué.

Pour le deuxième point `URI.encode`, bien vu, j'ai remonté ce point dans https://github.com/keathley/finch/issues/137 car ça ne sautait pas aux yeux. On verra leur réponse et on pourra faire des tests autour de cette partie spécifiquement sans souci, avec un peu de refactoring.

2021-05-08 08:41 UTC, thbar commented on apps/shared/lib/hasher.ex
> +    if status >= 200 and status < 400 do
Finch ne suit pas le redirect, j'ai été vérifier. Voir ma review générale.

2021-05-12 12:37 UTC, thbar commented
Finch n'évoluera pas donc il faut à minima qu'on fasse l'encode de notre côté: https://github.com/keathley/finch/issues/137. Plutôt tenté de faire une PR séparée pour ce point avec un test éventuellement (pas forcément utile).

2021-06-08 08:24 UTC, fchabouis commented
The headers always come before the body, and the status before the headers. See the HTTP specification, section "4.1 Message Types".

The format of a generic HTTP message is :

        generic-message = start-line
                          *(message-header CRLF)
                          CRLF
                          [ message-body ]
        start-line      = Request-Line | Status-Line

For a response, start-line contains the Status-Line. It must be followed by the headers, and then the eventual message body.

2021-06-09 09:53 UTC, fchabouis commented
@thbar j'ai repris cette PR, ça vaudrait le coup qu'on en discute par téléphone ensemble je pense.

J'ai aussi lancé le calcul du hash sur l'ensemble de nos ressources, ce qui donnait 34 crashs et 2270 succès.

Les crashs ont des causes variées (ressource ftp, des handshakes qui se passent mal, des connexions closed par le serveur).

2021-06-22 10:57 UTC, thbar approved these changes
À première (re)-vue ça me va ; peut-être juste reprendre la doc de la PR (ce qui est tout en haut) pour expliquer rapidement ce qu'on fait et pourquoi, maintenant que c'est fait.

2021-06-22 12:27 UTC, merged