WIP Envoyer des notifications en cas de nouveaux commentaires
etalab/transport-site pull request #1637
Opened 2021-05-12 16:24 UTC by fchabouis

Ajout d'une nouvelle tâche pour le scheduler : chaque jour, il va regarder pour chaque dataset le timestamp du dernier commentaire posté. S'il est plus récent que celui stocké en base, le dataset sera mentionné dans un email à l'équipe.

Il reste à faire : 

- [ ] ajout du champ dans la table dataset
- [ ] création de la tâche pour le scheduler
- [ ] écriture des fonctions permettant de récuper le timestamp du dernier commentaire
- [ ] la partie envoie de mail
- [ ] mise sous tests de la tâche

2021-05-20 14:54 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +          |> Discussions.comments_posted_after(current_ts)
suggestion : ramener ces fonctions dans ce module

2021-05-20 14:59 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +          "contact@transport.beta.gouv.fr",
mettre dans la config ?

2021-05-20 15:02 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +    case number_new_comments do
suggestion : couper la fonction en 2 (générer une liste, puis gérer le resultat)

2021-05-20 15:04 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +        nil ->
découpage ?

2021-05-20 15:13 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +    Repo.update(changeset)
gestion de l'erreur de update ?

2021-05-20 15:13 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +    changeset = Ecto.Changeset.change(dataset, %{latest_data_gouv_comment_timestamp: timestamp})
ecto multi ?

2021-05-20 15:19 UTC, fchabouis commented on apps/transport/test/transport/comments_checker_test.exs
> +        number_new_comments_2 = CommentsChecker.check_for_new_comments()
séparer dans un nouveau block with_mock ?

2021-05-25 08:52 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +    case number_new_comments do
ok

2021-05-25 13:34 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +          "contact@transport.beta.gouv.fr",
ok

2021-05-25 13:34 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +        nil ->
ok

2021-05-25 13:35 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +    Repo.update(changeset)
notification sentry en cas de probleme d'update (mais ça ne devrait pas arriver).

"famous last words" comme dirait @thbar

2021-05-25 13:37 UTC, fchabouis commented on apps/transport/lib/transport/comments_checker.ex
> +    changeset = Ecto.Changeset.change(dataset, %{latest_data_gouv_comment_timestamp: timestamp})
En fait ecto.multi semble faire des transactions individuelles, mais apporte surtout la garantie que si l'une d'entre elles échoue, toutes les précédentes qui sont passées sont rollbackées. Utile quand on veut supprimer un utilisateur par exemple et toutes ses traces, mais qu'on ne veut pas se retrouver dans un état intermédiaire. Ici je garde donc des transactions individuelles.

2021-05-25 13:39 UTC, fchabouis commented on apps/transport/test/transport/comments_checker_test.exs
> +        number_new_comments_2 = CommentsChecker.check_for_new_comments()
ok

2021-05-25 15:31 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/email/index.html.eex
> +            <%= link("voir la discussion", to: "https://demo.data.gouv.fr/fr/datasets/#{datagouv_id}/#discussion-#{comment["discussion_id"]}") %>
ah oui merci bien vu !

2021-05-27 12:47 UTC, thbar requested changes
Beau travail ! Je vote juste pour changer le type utilisé pour le timestamp si tu es OK, et déployer.

2021-05-27 12:47 UTC, thbar commented on apps/db/lib/db/dataset.ex
> +    field(:latest_data_gouv_comment_timestamp, :naive_datetime_usec)
@fchabouis j'avais zappé ce point: il est préférable d'utiliser les `utc_datetime_usec` ici, car cela aura un côté "vérifiant" de la zone. La team Ecto a indiqué (https://elixirforum.com/t/why-use-utc-datetime-over-naive-datetime-for-ecto/32532/4?u=thbar) qu'ils auraient préféré faire que ça soit le cas par défaut.

2021-05-27 12:47 UTC, thbar commented on apps/db/priv/repo/migrations/20210512142927_add_discussion_timestamp.exs
> +      add(:latest_data_gouv_comment_timestamp, :naive_datetime_usec)
Voir point plus haut sur `utc_datetime_sec`.

2021-05-27 12:47 UTC, thbar commented on apps/transport/lib/mailjet/client.ex
> +  def payload!(from_name, from_email, reply_to, topic, text_body, html_body \\ nil) do
Remarque mineure et sans impact ici: j'aime bien faire en sorte qu'un ajout de paramètre se traduise par une rétro-compatibilité, pour éviter les ratés de mise à jour. Là je pense que c'est le cas (l'ancien body était peut-être déjà du "texte").

On voit qu'il y a peut-être aussi trop de paramètres, qu'on gagnerait peut-être à passer des keywords arguments ou je ne sais pas à terme.

Pas de besoin de changer quoi que ce soit, je vais mouliner ma propre réflexion pour les prochains cas qui se présenteront dans la codebase.

2021-05-27 12:47 UTC, thbar commented on apps/transport/lib/transport/comments_checker.ex
> +    |> Repo.all()
Dans le futur on verra comment utiliser davantage de "streaming" pour éviter de charger tout en RAM, vu que c'est un meilleur pattern, mais là ça ne pose pas de problème a priori.

2021-05-27 12:47 UTC, thbar commented on apps/transport/lib/transport/comments_checker.ex
> +    with {:error, _changeset} <- update do
Pas besoin de changer pour ce tour, mais je me dis que vérifier que l'instrumentation Sentry capture les crashs de process, et utiliser plutôt un `update!` ici, sera peut-être un meilleur pattern dans le futur.

2021-05-27 12:47 UTC, thbar commented on apps/transport/lib/transport/comments_checker.ex
> +    |> Enum.flat_map(fn d -> d["discussion"] end)
On peut DRY-er le code un peu en faisant un appel à la méthode précédente pour ne pas répéter le code.

2021-05-27 13:08 UTC, thbar approved these changes
Au final après discussion off avec @fchabouis, la raison de la non utilisation d'un champ UTC est que la timezone de la data sur "data gouv" (d'où nous prenons cette donnée) n'est pas forcément fiable à ce stade.

@fchabouis a remonté l'échange https://github.com/etalab/data.gouv.fr/issues/171 qui mène à https://github.com/opendatateam/udata/issues/1046.

Je me suis abonné aux deux issues pour les suivre dans le temps.

Beau boulot, on merge !

2021-05-27 13:16 UTC, merged