Ajout de région : Nouvelle caledonie
etalab/transport-site pull request #1682
Opened 2021-06-23 15:43 UTC by fchabouis

Le but de l'opération est d'ajouter la nouvelle-calédonie à la carte stats :

![image](https://user-images.githubusercontent.com/15341118/123127074-3c57fd80-d44a-11eb-8de1-51f774ccf274.png)

Je rajoute la région via une migration pour garder une trace et rendre l'opération réversible, mais j'ai l'impression que les autres régions (hormi la région "nationale") ont été rajoutées directement en base.

On pourra par la suite rattacher le dataset https://transport.data.gouv.fr/datasets/reseau-taneo-1/ à la région fraichement créée.

2021-06-23 15:53 UTC, thbar requested changes
On dirait qu'il manque un bout !

2021-06-23 15:53 UTC, thbar commented on apps/db/priv/repo/migrations/20210623140048_add-nouvelle-caledonie.exs
> +defmodule :"Elixir.DB.Repo.Migrations.Add-nouvelle-caledonie" do
C'est curieux comme nommage (auto-généré je suppose) ?

2021-06-23 15:53 UTC, thbar commented on apps/db/priv/repo/migrations/20210623140048_add-nouvelle-caledonie.exs
> +      insert into region (nom, geom) values ('Nouvelle-Calédonie', 'MultiPolygon (((166.489958 -22.222429, 166.489325 -22.223471, 166.494259 -22.224151, 166.491392 -22.226864, 166.495365 -22.225801,
C'est vide ici ! Un oubli de commit ?

2021-06-23 15:54 UTC, thbar commented
Les tests ne passent pas actuellement.

2021-06-24 06:45 UTC, fchabouis commented on apps/db/priv/repo/migrations/20210623140048_add-nouvelle-caledonie.exs
> +      insert into region (nom, geom) values ('Nouvelle-Calédonie', 'MultiPolygon (((166.489958 -22.222429, 166.489325 -22.223471, 166.494259 -22.224151, 166.491392 -22.226864, 166.495365 -22.225801,
c'est 

```
execute """
 sql statement
"""
```
Je rate peut-être quelque chose mais ça m'a l'air bon...

2021-06-24 06:49 UTC, fchabouis commented on apps/db/priv/repo/migrations/20210623140048_add-nouvelle-caledonie.exs
> +defmodule :"Elixir.DB.Repo.Migrations.Add-nouvelle-caledonie" do
ah oui c'est pas jojo, je corrige :)

2021-06-24 14:23 UTC, thbar commented on apps/db/priv/repo/migrations/20210623140048_add-nouvelle-caledonie.exs
> +      insert into region (nom, geom) values ('Nouvelle-Calédonie', 'MultiPolygon (((166.489958 -22.222429, 166.489325 -22.223471, 166.494259 -22.224151, 166.491392 -22.226864, 166.495365 -22.225801,
Il y a un bug sur GitHub (mode diff qui n'affiche rien là chez moi), je leur remonterai.

2021-06-24 14:23 UTC, thbar approved these changes

2021-06-24 14:29 UTC, thbar commented
Je déploie, bravo @fchabouis !

2021-06-24 14:29 UTC, merged