Affichage du schéma d'une ressource si dispo
etalab/transport-site pull request #1690
Opened 2021-06-30 14:29 UTC by fchabouis

Si un producteur de donnée spécifie suivre un schéma pour une ressource, on l'affiche dans la page dataset, et on ajoute un lien vers la définition du schéma.

![image](https://user-images.githubusercontent.com/15341118/123978556-3f11a000-d9c0-11eb-8ec3-979288eeddf8.png)

On stocke l'information en base au moment de l'import.

2021-06-30 15:10 UTC, thbar requested changes
Si j'ai compris cette notion de schéma est importée depuis Data Gouv ? Si c'est le cas, est-ce qu'on pourrait faire en sorte que le test d'import vérifie ce point ?

Sinon rien à ajouter :smile:

2021-06-30 15:10 UTC, thbar commented on apps/db/priv/repo/migrations/20210630130031_add_resource_schema.exs
> +      add :schema, :string
Je me suis demandé si ce nom était réservé, apparemment ce n'est plus le cas (les schemas existent dans Postgres)

https://www.postgresql.org/docs/current/sql-keywords-appendix.html

2021-07-01 06:49 UTC, fchabouis commented on apps/transport/lib/transport_web/views/dataset_view.ex
> +    "https://schema.data.gouv.fr/#{schema_name}/latest.html"
Bonne remarque, j'ai l'impression que c'est un trou dans la raquette, on a le nom du schéma, pas sa version. Quand on spécifie un schéma dans data.gouv.fr pour une ressource, on spécifie juste le schéma pas sa version je crois :(
Je vais poser la question sur le repo data.gouv.fr

2021-07-01 06:57 UTC, fchabouis commented on apps/transport/lib/transport_web/views/dataset_view.ex
> +    "https://schema.data.gouv.fr/#{schema_name}/latest.html"
https://github.com/etalab/data.gouv.fr/issues/302

2021-07-01 08:55 UTC, fchabouis commented
Ahah très bon, en rajoutant le test je me suis rendu compte que j'avais par erreur reverté le fichier import_data. Belle leçon sur l'utilité des tests :)

2021-07-01 14:55 UTC, thbar commented
Du coup après discussion avec @fchabouis et cf https://github.com/etalab/data.gouv.fr/issues/302, on garde la PR ouverte pour intégrer directement la version.

2021-07-01 15:12 UTC, fchabouis commented
j'ai intégré la version @thbar

2021-07-06 12:58 UTC, thbar approved these changes
Good !

2021-07-06 13:32 UTC, merged