1694 ajout dune carte de validation sur
etalab/transport-site pull request #1729
Opened 2021-08-06 09:03 UTC by andlio

2021-08-06 10:16 UTC, fchabouis commented on apps/tmp.txt
> +
ce fichier s'est glissé dans la PR :)

2021-08-06 10:18 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/resource/_validation_summary.html.eex
> +        <span class="center">Aucune donnée géographique à afficher. Valider de nouveau le dataset pour les générer.</span>
il faudrait traduire ce message en anglais

2021-09-06 07:23 UTC, thbar reviewed
De façon générale, il faudra qu'on essaye de découper ce type de PR en plusieurs PR, car elle est relativement lourde et difficile à passer en revue (+916/-1122), quitte à abandonner la PR en cours de route et à en refaire une, une fois qu'on a réalisé ça.

Par exemple, on aurait peut-être gagné à faire une première PR qui faisait simplement un refactoring iso-fonctionnel, et qui merge ce point, et une deuxième qui ajoute la carte de validation.

2021-09-06 07:23 UTC, thbar commented on apps/shared/lib/data_visualization.ex
> +  @geojson_converter_url "https://convertisseur.transport.data.gouv.fr/gtfs2geojson_sync"
@andlio cette url devrait être en configuration dans `config/config.exs`, et récupérée via `Application.fetch_env!`, tant que possible (ça permet de remplacer le convertisseur par quelque chose de local facilement si besoin).

2021-09-06 07:23 UTC, thbar commented on apps/shared/lib/validation/gtfs_validator.ex
> +  def impl, do: Application.get_env(:transport, :gtfs_validator, Shared.Validation.GtfsValidator)
Il faut préférer `fetch_env!` pour lever une erreur claire quand la configuration est vide.

2021-09-06 13:01 UTC, fchabouis commented on apps/shared/lib/validation/gtfs_validator.ex
> +  def impl, do: Application.get_env(:transport, :gtfs_validator, Shared.Validation.GtfsValidator)
Ici on avait renseigné :gtfs_validator dans la config de test uniquement, et ça retombe par défaut sur le vrai module si la variable n'est pas settée (ailleurs qu'en tests donc).

Tu préfères qu'on enlève le comportement par défaut et qu'on renseigne explicitement la variable dans la config de prod ?

2021-09-06 13:13 UTC, thbar requested changes

2021-09-06 13:13 UTC, thbar commented on config/gtfs_validator.exs
>  # Configure GTFS Validator
Le changement ci-dessous est problématique, car à présent le fait de spécifier `GTFS_VALIDATOR_URL` en production ou en staging n'aura plus d'effet.

Cela veut dire qu'on perd (régression) la capacité à changer temporairement l'url du validateur via ENV, ce qui est utile pour tester un changement ou autre.

Par ailleurs ça va être source de confusion car le ENV de prod/staging fait apparaître actuellement cette url.

Ma suggestion est de remettre quelque chose comme:

```elixir
config :transport, gtfs_validator_url: System.get_env("GTFS_VALIDATOR_URL", l'url par défaut)
```

Peut-être directement au niveau de `config.exs`, on peut enlever `gtfs_validator.exs` en tant que fichier, et supprimer l'entrée associée dans `dev.exs` aussi.

On gardera la possibilité d'overrider avec `dev.secret.exs` en local.

Si besoin pour les tests par rapport à d'éventuelles cassettes, on peut remettre une valeur dans `test.exs` au pire.

@andlio voilà !

2021-09-06 13:17 UTC, thbar commented on apps/shared/lib/validation/gtfs_validator.ex
> +  def impl, do: Application.get_env(:transport, :gtfs_validator, Shared.Validation.GtfsValidator)
@fchabouis j'avais mal lu, il y a 3 paramètres et une valeur par défaut, donc pas besoin ! Merci pour la réponse.

2021-09-07 07:09 UTC, andlio commented on config/gtfs_validator.exs
>  # Configure GTFS Validator
Bien vu !
C'est corrigé !

2021-09-07 08:35 UTC, thbar commented on apps/transport/lib/transport_web/templates/resource/_validation_summary.html.eex
> +        <span class="center">Aucune donnée géographique à afficher. Valider de nouveau le dataset pour les générer.</span>
@andlio as-tu vu ce point ?

2021-09-07 08:39 UTC, thbar approved these changes
J'approuve pour ce tour, par contre à l'avenir il faudra vraiment penser au point suivant que j'avais mis en commentaire : essayer d'avoir des PR plus légères, quitte à accepter en cours de route de fermer le travail en cours, et refaire plusieurs PR.

> De façon générale, il faudra qu'on essaye de découper ce type de PR en plusieurs PR, car elle est relativement lourde et difficile à passer en revue (+916/-1122), quitte à abandonner la PR en cours de route et à en refaire une, une fois qu'on a réalisé ça.
>
> Par exemple, on aurait peut-être gagné à faire une première PR qui faisait simplement un refactoring iso-fonctionnel, et qui merge ce point, et une deuxième qui ajoute la carte de validation.

En l'état c'était difficile à reviewer, et je ne suis pas sûr à 100% de comprendre tout non plus.

Bon boulot sinon !

2021-09-14 11:53 UTC, merged