Activation tuile stationnement cyclable + désactivation tuile "Car and motorbike sharing"
etalab/transport-site pull request #1781
Opened 2021-09-14 19:29 UTC by andlio

Avant:
<img width="1124" alt="Capture d’écran 2021-09-14 à 21 27 18" src="https://user-images.githubusercontent.com/6974621/133321594-5614ef81-9bad-40de-a471-882c3b88c3b3.png">

Après:
<img width="1120" alt="Capture d’écran 2021-09-14 à 21 28 56" src="https://user-images.githubusercontent.com/6974621/133321720-c04d4577-26f0-42ab-8933-b5936ec8ee84.png">

Closes #1772

2021-09-15 07:46 UTC, fchabouis requested changes
Cool @andlio !
Est-ce que tu as pu tester en local que tu pouvais ajouter un nouveau jeu de données dans cette catégorie et qu'il était bien compté dans la tuile correspondante de la home ? (Si tu ne vois pas comment on fait ça je te montrerai).
J'ai fait une petite remarque sur le nom du svg.
Sinon je pense que c'est tout bon :+1:

2021-09-15 07:46 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/page/index.html.eex
> +        <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bicycle-parking.svg") %>" alt="" />
On pourrait nommer l'image comme la catégorie (bike-parking)

2021-09-15 18:30 UTC, andlio commented on apps/transport/lib/transport_web/templates/page/index.html.eex
> +        <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bicycle-parking.svg") %>" alt="" />
J'ai hésité effectivement, mais j'ai eu du mal à identifier un standard. Par exemple :
```html
<a class="tile" href="<%= dataset_path(@conn, :index, type: "bike-scooter-sharing") %>">
      <img class="tile__icon" src="<%= static_path(@conn, "/images/icons/bicycle-scooter.svg") %>" alt="" />
      <div class="tile__text">
        <h4 class=""><%= dgettext("page-index", "Bike and scooter sharing") %></h4>
        <div>
                <%= dngettext("page-index", "dataset", "datasets", @count_by_type["bike-scooter-sharing"] || 0) %>
        </div>
      </div>
</a>
```

Je vais renommer l'image.

2021-09-16 07:22 UTC, andlio commented
> Est-ce que tu as pu tester en local que tu pouvais ajouter un nouveau jeu de données dans cette catégorie et qu'il était bien compté dans la tuile correspondante de la home ? (Si tu ne vois pas comment on fait ça je te montrerai).

Je confirme. L'ajout d'un dataset incrémente le compteur 👍

2021-09-16 08:30 UTC, fchabouis approved these changes
Et une nouvelle catégorie !
Bravo :)

2021-09-16 09:20 UTC, merged