Ajout d'un lien vers la section "ressources historisées"
etalab/transport-site pull request #1914
Opened 2021-11-10 11:31 UTC by fchabouis

closes #1619 

J'en profite pour renommer la section "historique" par "ressources historisées", ce qui me parait plus parlant.

Pour le moment j'ai mis le message uniquement pour les ressources GTFS, car il n'y a qu'elles qu'on historise.

![image](https://user-images.githubusercontent.com/15341118/141105506-aa94ad45-1d9a-4de8-8fcb-4ca96795ce85.png)

2021-11-10 14:44 UTC, AntoineAugusti requested changes

2021-11-10 14:44 UTC, AntoineAugusti commented on apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
> +msgid "Past versions of the dataset resources are available in the  %{link} section."
Il y a 2 espaces avant `%{link}` et ça ne semble pas être le cas dans la vue (faut changer les autres `.po`)

2021-11-15 08:43 UTC, fchabouis commented on apps/transport/priv/gettext/en/LC_MESSAGES/page-dataset-details.po
> +msgid "Past versions of the dataset resources are available in the  %{link} section."
bien vu merci

2021-11-15 08:45 UTC, fchabouis commented on apps/transport/priv/gettext/fr/LC_MESSAGES/page-dataset-details.po
> +msgstr "Des versions précédentes des ressources de ce dataset sont disponibles dans la section %{link}."
je vais mettre jeu de données, tu as raison.

2021-11-15 09:01 UTC, AntoineAugusti approved these changes

2021-11-15 09:02 UTC, merged