Visualisation de métadonnées GBFS
etalab/transport-site pull request #1915
Opened 2021-11-10 14:39 UTC by AntoineAugusti

Suite de https://github.com/etalab/transport-site/pull/1905. Utilise les métadonnées GBFS introduites dans cette PR.

Affiche sur la page d'un JDD, pour les ressources GBFS :
- le ttl
- si la validation est correcte/le nombre d'erreurs + un lien vers le rapport de validation dans tous les cas
- les versions du flux GBFS

2021-11-15 11:06 UTC, fchabouis requested changes
J'ai mis quelques questions et suggestions.
Ça va être cool :)

2021-11-15 11:06 UTC, fchabouis commented on apps/transport/lib/transport_web/views/dataset_view.ex
>    def summary_class(%{count_errors: 0}), do: "resource__summary--Success"
Peut-être un petit commentaire disant que ces cas correspondent à la validation des GTFS par notre validateur. C'était implicite jusqu'à présent. Mais maintenant que ça se démocratise :)

2021-11-15 11:06 UTC, fchabouis commented on apps/transport/lib/transport_web/views/dataset_view.ex
> +  def errors_count(%Resource{format: "gbfs"}), do: nil
donc errors_count peut effectivement renvoyer nil (pour la remarque précédente sur "during validation")

2021-11-15 15:12 UTC, AntoineAugusti commented
@fchabouis J'ai pris en compte tes commentaires dans mon dernier commit.

- Lien vers la documentation GBFS en fonction de la version
- Différentiation des labels
- Commentaires supplémentaires
- Faire en sorte de ne pas avoir de texte orphelin

J'attends que #1905 soit mergée pour inclure le nom du feed utilisé dans le tooltip du TTL

2021-11-16 08:22 UTC, AntoineAugusti commented
@fchabouis Je viens d'inclure le nom du feed utilisé pour calculer le TTL dans la tooltip dans https://github.com/etalab/transport-site/pull/1915/commits/a1faea4da75f165750c0a87393d570180161e35b

2021-11-16 13:16 UTC, thbar approved these changes
Ca me paraît bon en lecture rapide. Cool d'afficher ça !

2021-11-16 13:29 UTC, merged