Affichage des VLS par AOM
etalab/transport-site pull request #1993
Opened 2021-12-15 10:43 UTC by AntoineAugusti

Avec la publication récente de JDD VLS, on se retrouve à avoir plusieurs JDD dans une même ville. Dans ce cas, notre carte n'affiche qu'un seul JDD.

J'ai adapté le code pour utiliser une visualisation similaire aux données théoriques, regroupé par AOM. On affiche donc les VLS "dans cette AOM" à présent.

⚠️ Il faudra changer les JDD existants pour renseigner le champ AOM @Miryad3108 

![image](https://user-images.githubusercontent.com/295709/146172149-8654eaf7-1fb0-4ea9-be56-fd3143ee1e43.png)

2021-12-15 14:42 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
>    end
J'ai fait ce travail ici car `render_features` n'est adapté que pour des requêtes concernant les AOMs

2021-12-15 14:42 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
> +  defp render_features(conn, query, cache_key) do
Avec la nouvelle méthode en dessous, `cache_key` est toujours présent

2021-12-16 08:18 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
> +        "properties" => Map.take(r, Enum.filter(Map.keys(r), fn k -> k != "geometry" end))
Il y a de nouvelles méthodes en Elixir 1.13 pour simplifier ça https://hexdocs.pm/elixir/Map.html#reject/2

2021-12-16 08:32 UTC, fchabouis requested changes
J'ai testé en local, ça marche bien. Le seul point a vraiment changer, c'est le titre de la section dans les stats, le reste est à ta discrétion :)

2021-12-16 08:32 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/stats/index.html.eex
>                <a href="#real-time-bikes"><i class="fa fa-link fa-small"></i></a>
faudrait changer le titre => ~~Vélos~~ Véhicules libre service

2021-12-16 08:32 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/stats/index.html.eex
> +              Les données, rafraîchies régulièrement, permettent de connaître :
Je trouve que "régulièrement" fait perdre la notion de flux temps réel. On pourrait mettre "Les données, constamment mises à jour, ..." ou "Les données, mises à jour en continu, ..."

2021-12-16 08:32 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/stats/index.html.eex
> +                <li>La liste des véhicules accessibles en libre-service sans station</li>
suggestion : ajouter les zones de geofencing ?

2021-12-16 08:32 UTC, fchabouis commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
> +        names: fragment("array_agg(?)", dataset.spatial),
suggestion : trier les noms par ordre alphabétique, avec un "order by spatial" dans le array_agg

2021-12-16 08:32 UTC, fchabouis commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
> +        names: fragment("array_agg(?)", dataset.spatial),
stylé le array_agg

2021-12-16 08:39 UTC, thbar approved these changes
Modulo les mêmes petites remarques que @fchabouis ça me paraît top ; j'ai testé en local, tout roule.

Bravo pour le test, qui verrouille bien le fonctionnement de la partie basse, c'est le bienvenu !

2021-12-16 08:52 UTC, AntoineAugusti commented
Merci pour la review ! J'ai pris en compte vos commentaires dans le dernier commit et je m'apprête à merger. 🤝 🚲 🛴

2021-12-16 08:55 UTC, merged