Ajout job pour répliquer backups de base de données
etalab/transport-site pull request #2002
Opened 2021-12-16 13:00 UTC by AntoineAugusti

Ajout d'un job pour répliquer les sauvegardes de la base de données sur un autre Cellar.

- Source : Cellar `Backups`, à Paris en infrastructure Clever Cloud
- Destination : Cellar `backups-infra-ovh-roubaix`, à Roubaix chez OVH (mais toujours sur notre compte Clever Cloud)

Garde les 10 sauvegardes les plus récentes. Le job est fait avec GitHub Actions qui utilise [s3cmd](https://s3tools.org/s3cmd)

2021-12-16 13:00 UTC, AntoineAugusti commented on .github/workflows/backup_db.yml
> +  push:
Je supprimerai ceci avant de merger, c'était pour bien exécuter le job sur la branche et vous laisser inspecter.

2021-12-16 13:07 UTC, AntoineAugusti commented
Un output de job où vous verrez bien l'upload (libre à vous de vérifier avec un client S3 !) https://github.com/etalab/transport-site/runs/4547660045?check_suite_focus=true. Le dernier commit ne fait rien car les fichiers sont les mêmes.

2021-12-16 14:06 UTC, thbar requested changes
J'en ai parlé au téléphone avec @AntoineAugusti, voilà un peu mes éléments par écrit.

Je préfèrerais une solution où:

- on dispose d’un bucket S3 hébergé complètement ailleurs (“défense en couches” dans le sens où un hack d’un compte CleverCloud seul ne permettra pas d’effacer les backups également comme ici)
- on utilise un utilisateur S3 autorisé uniquement à écrire (le même hack ne permettra également pas d’effacer les backups ; ceci ne protégeant pas du hack du deuxième système destination, mais ajoute une couche) ; j’ai l’impression que [Scaleway](https://www.scaleway.com/en/docs/storage/object/api-cli/bucket-policy/) permet ça - tout en notant bien que les contraintes de carte bleue sur beta gouv sont présentes
- on conserverait les backups bien plus longtemps (le stockage ne coûte pas cher, et si on détecte une corruption de données à un instant t, elle peut traîner un moment)
- on ne partage pas des credentials capables d’écrire dans le bucket d’origine ou de destination avec un environnement de plus (GitHub), car ça élargit la surface d’attaque (on peut mitiguer ça partiellement avec les [droits](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-specific-actions-to-run) comme discuté avec Antoine, toutefois ça fait qu’on inclut les super-admins Etalab dans ceux qui peuvent à présent être ciblés pour effacer nos backups 

La PR actuelle améliore le backup (dans le sens où même si il reste chez CC en façade et donc un downtime chez eux pourrait avoir un impact pour une raison plus ou moins imprévisible, il est géographiquement stocké ailleurs), et ça c'est cool, toutefois je suis moyen chaud avec le partage de credentials (même en les protégeant) "juste pour ça", là où un cron sur le serveur lui-même enlèverait un point d'attaque relativement facilement.

À discuter avec @fchabouis pour avoir son input!

2021-12-28 15:39 UTC, fchabouis commented
Avec cette base, il peut nous arriver plusieurs problèmes :
1.  pour une raison qcq, son contenu est dégradé
2. CC perd notre notre base et ses backups définitement suite à un événement type incendie
3. les services CC tombent de manière temporaire, le PAN est down, on veut le redémarrer ailleurs.
4. une personne malveillante arrive à supprimer la base et ses backups
5. ...autre chose ?

Pour le 1., on a maintenant des backups sur une durée assez longue.
La PR actuelle nous protège normalement de 2., l'incendie chez CC.
Mais peut-être pas de 3, car l'adresse du cellar d'OVH est `cellar-fr-north-hds-c1.services.clever-cloud.com`, en cas de problème de DNS chez eux, on pourrait ne pas y avoir accès ?
Il est vrai que nos access key de cellar se retrouvent a un endroit de plus, ce qui rend 4. plus "facile".

Je serais plutôt partant pour faire le backup complètement ailleurs, idéalement chez un provider qui  nous permettrait aussi de redéployer l'application chez lui facilement en cas de crise, pour que tout soit au même endroit (notre safe house :house: )

2022-01-10 10:13 UTC, AntoineAugusti commented
Après discussion, on va plutôt voir comment faire pour faire des sauvegardes de base de données sur un autre hébergeur.

Les problèmes qu'on avait là :
- pas de possibilité d'avoir des clés en read only ou write only
- un accès potentiel aux valeurs des clés pour des personnes en dehors de l'équipe tech
- on ne sait pas si le fait d'utiliser un autre DC chez CleverCloud isole vraiment au niveau du réseau/DNS

Je ferme donc la PR et j'ai supprimé les valeurs secrètes enregistrées dans GitHub.

2022-01-10 10:13 UTC, closed without merging

2022-01-10 10:14 UTC, AntoineAugusti commented
La liste des actions exécutées sur GitHub, https://github.com/etalab/transport-site/actions, ne montre pas que quelqu'un a réussi à lire les clés.

J'ai supprimé l'addon sur CC.