Unlock: vérifie présence TTL sur les clés
etalab/transport-site pull request #2013
Opened 2021-12-24 16:37 UTC by AntoineAugusti

- Ajout d'une méthode vérifiant la présence d'un TTL sur les clés du proxy toutes les 5s
- Ajout de tests

2021-12-27 08:48 UTC, AntoineAugusti commented on apps/unlock/lib/enforce_ttl.ex
> +  A module running a method every 5s to make sure that all proxy keys have a TTL set.
Pourrait être moins souvent, mais le code est très léger

2021-12-27 08:48 UTC, AntoineAugusti commented on apps/unlock/lib/enforce_ttl.ex
> +  defp enforce_ttl(_key, _res), do: nil
On peut écrire ça mieux ?

2021-12-27 08:48 UTC, AntoineAugusti commented on apps/unlock/test/shared_test.exs
> +defmodule Unlock.SharedTest do
Pas vraiment lié à cette PR, mais commençait à manquer de tests

2021-12-28 16:11 UTC, fchabouis commented
Je ne voudrais pas qu'on cache un problème sous le tapis, qu'il soit chez nous ou chez Cachex. Je pense qu'il faudrait au moins se faire une notif Sentry si on trouve une entrée de cache sans TTL.

Je vois aussi qu'il est possible de mettre un TTL par défaut dans un cache, via l'option :expiration (https://hexdocs.pm/cachex/ttl-implementation.html#key-expirations), ce qui aurait pu être une solution pas très couteuse pour s'assurer que tout le monde a un cache.

2021-12-28 16:19 UTC, fchabouis commented on apps/unlock/lib/enforce_ttl.ex
> +  def init(state) do
tu peux rajouter les `@impl true` pour le behavior (comme dans https://hexdocs.pm/elixir/GenServer.html#module-receiving-regular-messages)

2021-12-28 16:23 UTC, fchabouis commented on apps/unlock/lib/enforce_ttl.ex
> +  defp enforce_ttl(_key, _res), do: nil
je suis pas sûr

2021-12-28 16:30 UTC, fchabouis requested changes
Cool l'utilisation du GenServer !
Il y a aussi l'option de mettre une expiration par défaut pour le cache.
Sinon on pourrait mettre l'expiration pour tout le monde et faire tourner le genserver avec des notifs Sentry en cas d'absence de TTL pour se rassurer.
En tout cas, si on garde le GenServer, j'aimerais bien avoir des notifs Sentry s'il doit faire du ménage à la main, parce que c'est pas normal.

2021-12-29 09:16 UTC, AntoineAugusti commented on apps/unlock/lib/config.ex
> +          Cachex.persist(cache_name(), @proxy_config_cache_key)
Il y a déjà un test pour s'assurer qu'il n'y a pas d'expiration sur cette clé. Cette ligne était nécessaire pour garder les tests au vert

2021-12-29 09:16 UTC, AntoineAugusti commented on apps/unlock/lib/enforce_ttl.ex
> +      Sentry.capture_message("Removed #{key} from cache. ttl was #{ttl} while config is #{ttl_config_value(key)}")
Message dans Sentry

2021-12-29 09:16 UTC, AntoineAugusti commented on apps/unlock/lib/enforce_ttl.ex
> +    ttl_over_config_value = is_integer(ttl) and ttl > ttl_config_value(key)
On verra pas de problème si jamais ça arrive sur une clé avec un TTL dans la config plus grand que la valeur par défaut.

Ça me parait acceptable, car c'est pas censé arriver d'une part, que le TTL par défaut est à 60s ce qui est pas mal pour du temps réel et que si ça arrive on va juste ne pas respecter le TTL une fois.

2021-12-29 09:16 UTC, AntoineAugusti commented
@fchabouis J'ai ajouté un TTL par défaut et j'ai mis un message dans Sentry si jamais une clé est supprimée

2021-12-29 12:50 UTC, fchabouis approved these changes
Cool merci !

2021-12-29 13:35 UTC, merged