Création classe ResourceSchema
etalab/transport-site pull request #2017
Opened 2021-12-28 13:02 UTC by AntoineAugusti

Ajout d'une classe `Transport.Shared.ResourceSchema` afin de devenir les noms des schémas et leurs versions pour les ressources.

- extraction du code existant, utilisation lors de l'import de données
- reconnaissance du schéma pour les ZFE pour les ressources où le schéma n'est pas renseigné sur data.gouv.fr

2021-12-28 13:03 UTC, AntoineAugusti commented on apps/shared/test/resource_schema_test.exs
> +  doctest Transport.Shared.ResourceSchema, import: true
J'ai découvert `import`, trop cool https://hexdocs.pm/ex_unit/ExUnit.DocTest.html#doctest/2

2021-12-28 16:35 UTC, fchabouis commented on apps/shared/lib/resource_schema.ex
> +
il manque le résultat

2021-12-28 16:36 UTC, fchabouis requested changes
y'a juste le test à corriger :+1:

2021-12-28 16:43 UTC, AntoineAugusti commented
Mais pourquoi j'ai pas eu une erreur 😢 C'est corrigé

2021-12-29 12:52 UTC, fchabouis commented
T'as vérifié qu'ils étaient effectivement lancés ? C'est vrai qu'on aurait pu s'attendre à une erreur...

2021-12-29 13:25 UTC, AntoineAugusti commented
@fchabouis Oui c'est bien lancé, je m'attendais juste à ce que quelque chose détecte l'erreur de syntaxe qui faisait qu'il manquait un test. Maintenant tout est bon.

2021-12-31 14:25 UTC, fchabouis approved these changes
:+1:

2021-12-31 14:25 UTC, merged