EnforceTTL uniquement sur le webserver
etalab/transport-site pull request #2019
Opened 2021-12-29 15:00 UTC by AntoineAugusti

Suite de https://github.com/etalab/transport-site/pull/2013, pour s'assurer que `Unlock.EnforceTTL` ne s'exécute que sur le webserver et non les workers.

2021-12-31 14:24 UTC, fchabouis requested changes

2021-12-31 14:24 UTC, fchabouis commented on apps/unlock/lib/application.ex
> +  defp webserver?, do: Application.fetch_env!(:transport, :webserver)
Il vaudrait mieux éviter d'aller chercher des variables de l'application `:transport` depuis `:unlock`.

Une manière de le faire serait d'ajouter à runtime.exs la config suivante : `config :unlock,
  enforce_ttl: webserver
`
Et d'utiliser cette variable dans ce fichier  `Application.get_env(:unlock, enforce_ttl)` ce qui laisse Unlock ignorant de toute notion de webserver.

2022-01-03 15:22 UTC, AntoineAugusti commented on apps/unlock/lib/application.ex
> +  defp webserver?, do: Application.fetch_env!(:transport, :webserver)
Merci pour la suggestion, c'est fait !

2022-01-03 16:05 UTC, fchabouis approved these changes
C'est parti !

2022-01-03 16:05 UTC, merged