Validation à la demande d'un fichier ou d'un flux
etalab/transport-site pull request #2186
Opened 2022-03-03 15:00 UTC by AntoineAugusti

Cette PR modifie la validation à la demande pour intégrer le GBFS dans la page existante. Elle prépare à la possibilité de valider des fichiers ou des URLs distantes, particulièrement utile pour du GTFS-RT par exemple.

Cette page est désormais un composant LiveView pour permettre de changer le type d'input en fonction du type de données à valider.

La validation d'un flux GBFS est désormais enregistrée en tant que `DB.Validation` dans le but d'avoir des statistiques. Ce n'est pas encore comme les autres validations à la demande (validation dans un job Oban, enregistrement des métadonnées en base de données) pour limiter la taille de la PR.

L'ancienne URL de validation GBFS redirige et sélectionne automatiquement le type de données approprié.

Les liens pour valider à nouveau une ressource invalide sélectionne automatiquement le type de données approprié (si une ZFE est invalide, le lien sélectionne le type ZFE).

https://user-images.githubusercontent.com/295709/157009368-b71c1130-f570-4c0d-9dc7-ed9ec5a2a40b.mov

2022-03-07 10:05 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/live/on_demand_validation_select_live.ex
> +defmodule TransportWeb.Live.OnDemandValidationSelectLive do
Bien plus compliqué à écrire que les 50 lignes du fichier 🥵

2022-03-07 10:05 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/templates/gbfs_analyzer/index.html.eex
> -    <div class="pb-48">
Suppression du formulaire pour valider à nouveau.

2022-03-07 10:05 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/templates/gbfs_analyzer/index.html.eex
> +    <%= unless is_nil(validation) do %>
Affichage de la validation avant les métadonnées

2022-03-08 08:24 UTC, fchabouis commented on apps/transport/lib/transport_web/controllers/validation_controller.ex
> +    [{"GTFS", "gtfs"}, {"GBFS", "gbfs"}] ++ schemas
je sais pas si tu connais le truc, que si tu veux utiliser les opérateurs dans un pipe, tu peux le faire avec `Kernel`

```
iex(2)> [1,2] |> Kernel.++([3])
[1, 2, 3]
```

2022-03-08 08:27 UTC, fchabouis commented on apps/transport/lib/transport_web/live/on_demand_validation_select_live.html.heex
> +    <article class="">
`class` est vide

2022-03-08 08:38 UTC, fchabouis commented on apps/transport/lib/transport_web/controllers/validation_controller.ex
> +  def validate(%Plug.Conn{} = conn, %{"upload" => %{"url" => url, "type" => "gbfs"} = params}) do
il faudrait remplir la colonne `date` aussi 
![image](https://user-images.githubusercontent.com/15341118/157199228-0437e510-6a97-484c-a91f-842f0edc577b.png)

2022-03-08 08:45 UTC, fchabouis commented
Il y a un effet un peu troublant pour la validation des GBFS maintenant, c'est que lorsqu'on clique sur valider, on reste sur la page, mais le contenu du champ disparaît. Ca donne l'impression que ça ne fonctionne pas pendant quelques secondes.
![validate](https://user-images.githubusercontent.com/15341118/157200216-dc5db236-d455-466a-959c-39913cfff6b0.gif)

2022-03-08 08:52 UTC, fchabouis commented
Ce n'est pas directement lié à cette PR mais je le remarque en testant. Le site reste avant tout conçu prioritairement pour les réutilisateurs des données, du coup je trouve que le message suivant qui s'adresse en réalité au producteur risque d'embrouiller un réutilisateur qui risque de ne pas comprendre pourquoi il voit ce message.

![image](https://user-images.githubusercontent.com/15341118/157201157-72f77baa-7676-49df-890c-308b8bd98f95.png)

J'aurais tendance à le mettre moins en avant, et à préciser qu'il s'adresse au producteur de la donnée.

Du style :
"Vous êtes le producteur de ces données ? Une fois vos erreurs réparées, vous pouvez vérifier que votre fichier est valide [en utilisant nos validateurs](https://transport.data.gouv.fr/validation).", mais plutôt en texte gris sous les erreurs.

2022-03-08 09:00 UTC, fchabouis requested changes
Quelques changement à faire (cf remarques plus haut).

Ça va faire une belle page unifiée de validation :+1:

2022-03-08 09:47 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/controllers/validation_controller.ex
> +  def validate(%Plug.Conn{} = conn, %{"upload" => %{"url" => url, "type" => "gbfs"} = params}) do
T'as raison, c'est fait ailleurs pour les autres formats https://github.com/etalab/transport-site/blob/748920c37eb1f7d0b90f323124e2c0169fce454e/apps/transport/lib/jobs/on_demand_validation_job.ex#L30

Merci

2022-03-08 09:48 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/controllers/validation_controller.ex
> +    [{"GTFS", "gtfs"}, {"GBFS", "gbfs"}] ++ schemas
Merci, je connaissais pas

2022-03-08 09:55 UTC, AntoineAugusti commented
@fchabouis Merci ! J'ai pris en compte tes commentaires dans le dernier commit.

- c'est vrai qu'il y a un petit lag quand on valide puis qu'on arrive à la page des résultats, je pense que ce sera amélioré quand on aura la passe "waiting screen" et validation en tâche de fond. Je pense que c'est la même expérience qu'actuellement.
- j'ai modifié le texte pour le bandeau incitant à valider à nouveau mais je souhaite le garder assez visible pour mettre en avant cette nouvelle fonctionnalité. À revoir dans quelques semaines quand cet outil sera rentré dans les habitudes ?

2022-03-08 10:46 UTC, fchabouis commented
Pour le moment ça fait comme ça, j'aimerais bien garder l'expérience actuelle, surtout que se sera l'objet de la présentation faite à Mobility Data le 23.
![validate_prod](https://user-images.githubusercontent.com/15341118/157223430-35f684b3-1d56-4879-8181-239a80880753.gif)

2022-03-08 12:45 UTC, AntoineAugusti commented
@fchabouis J'ai revu la gestion des changements des valeurs du formulaire (avec `changeset`) et l'UI de résultat de validation du GBFS 
![image](https://user-images.githubusercontent.com/295709/157240766-e90eb54f-1e2b-4f1d-862f-e66e11736f95.png)

2022-03-08 14:30 UTC, fchabouis approved these changes
Merci pour les changements @AntoineAugusti !

2022-03-08 14:30 UTC, merged