Licence mobilités pour Lyon
etalab/transport-site pull request #2194
Opened 2022-03-07 11:09 UTC by AntoineAugusti

Gestion de la "Licence mobilités" pour la métropole de Lyon.

- Valeur de `dataset.licence` adéquate pour les datasets concernés
- Affichage du nom de la licence et lien vers la description de la licence

2022-03-07 11:10 UTC, AntoineAugusti commented on apps/transport/lib/transport/import_data.ex
> -  def check_license(_), do: false
Code non utilisé

2022-03-07 11:10 UTC, AntoineAugusti commented on apps/transport/lib/transport/import_data.ex
> +    if org_name in orgs_with_mobility_license do
Tous les JDD publiés sur leur plateforme concernant la mobilité sont sous cette licence. On pourra avoir une règle plus fine à l'avenir si besoin.

2022-03-08 08:15 UTC, fchabouis requested changes
J'ai testé en local ça marche bien.
Peux tu rajouter en commentaire de la fonction `licence` le contexte ? J'ai peur que dans X mois, la raison de cette exception se soit perdue.
Dire que data.gouv.fr ne supporte pas cette licence, mais que nous on doit l'afficher quand même.

2022-03-08 08:17 UTC, fchabouis approved these changes

2022-03-08 08:20 UTC, AntoineAugusti commented
@fchabouis Tout à fait, j'ai ajouté quelques lignes de doc supplémentaires, merci !

2022-03-08 08:22 UTC, merged