Pas de validation en masse de ressources sur prochainement
etalab/transport-site pull request #2405
Opened 2022-05-19 10:23 UTC by fchabouis

Pour éviter de faire surchauffer le validateur GTFS.

2022-05-19 12:03 UTC, thbar commented
Je suis en train de regarder.

2022-05-19 12:16 UTC, thbar requested changes
C'est sweet de ménager le validateur :smile: il en a bien besoin.

En l'état je crois bien que la PR modifie le staging mais aussi le dév, et ça on ne veut pas forcément l'avoir je pense ?

Je me base sur la lecture du code (vite fait) et un peu aussi sur ceci:

```elixir
❯ mix run -e "IO.inspect Application.get_env(:transport, Oban), IEx.inspect_opts" 
[info] Booting in worker+webserver mode...
[info] Function passed as a handler with ID "oban-logger" is local function.
This mean that it is either anonymous function or capture of function without module specified. That may cause performance penalty when calling such handler. For more details see note in `telemetry:attach/4` documentation.

https://hexdocs.pm/telemetry/telemetry.html#attach-4
[debug] Loading Initial Jobs from Config
[debug] QUERY OK source="commune" db=0.5ms decode=0.8ms queue=0.5ms idle=7.7ms
SELECT c0."nom", c0."insee" FROM "commune" AS c0 []
[
  repo: DB.Repo,
  queues: [
    default: 2,
    heavy: 1,
    on_demand_validation: 1,
    resource_history_validation: 1
  ],
  plugins: [
    {Oban.Plugins.Pruner, [max_age: 86400]},
    {Oban.Plugins.Cron,
     [
       crontab: [
         {"0 2,8,14,20 * * *", Transport.Jobs.ResourceHistoryValidationJob}
       ]
     ]}
  ]
]
```

Ca me paraît préférable de rester sur le mode où aucun cron ne tourne en local, est-ce que ça te paraît bien ?

2022-05-24 07:22 UTC, fchabouis commented
Merci @thbar ce double jeu de variable MIX_ENV et APP_ENV m'avait désorienté.
Dis moi si le changement te convient.

2022-05-24 07:41 UTC, thbar approved these changes
@fchabouis ça a l'air tout bon maintenant ! Merci pour le correctif.

À terme je pense qu'il nous faudra un peu de test sur `runtime.exs` pour ne pas nous emmêler les pinceaux, sinon ce n'est pas forcément évident.

J'ai quelques idées sur comment faire ça, on verra si le sujet revient sur la table.

Merci pour ta PR !

2022-05-24 07:41 UTC, merged