Remplir le champ max_error pour les multi-validations GTFS
etalab/transport-site pull request #2464
Opened 2022-06-17 09:37 UTC by fchabouis

On va avoir besoin de ce champ pour brancher la carte de stats sur la multi validation (pour le moment elle est toujours branchée sur la validation v1 pour la carte de qualité des données)

Cette PR vient après #2454

2022-06-27 15:03 UTC, fchabouis commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +    {"NoError", 0}
Je met en cohérence les 2 fonctions `count_max_severity` et `get_max_severity_error` : si elles ne trouvent rien, elles renvoient un "NoError"

2022-06-27 15:04 UTC, fchabouis commented on apps/transport/lib/jobs/on_demand_validation_job.ex
> +          max_error: GTFSTransport.get_max_severity_error(validation),
le max_error est rempli pour les validations à la demande

2022-06-27 15:04 UTC, fchabouis commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +        max_error: get_max_severity_error(validations)
Il est rempli aussi pour les validations du site

2022-06-28 10:16 UTC, AntoineAugusti requested changes

2022-06-28 10:16 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
> +              <%= if severity == "NoError" do %>
Faudrait peut-être adapter le code pour la validation à la demande ici ? https://github.com/etalab/transport-site/blob/61611d9293b148cb0495d7f9e19e6fd80f679d4a/apps/transport/lib/transport_web/views/validation_view.ex#L11-L16

2022-06-28 15:17 UTC, fchabouis commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +    {"NoError", 0}
ok

2022-06-28 15:18 UTC, fchabouis commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +  def get_max_severity_error(_), do: nil
je pense qu'elle peut recevoir un `nil` éventuellement

2022-06-28 15:23 UTC, fchabouis commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +        max_error: get_max_severity_error(validations)
je rajoute un test dans `GtfsTransportValidatorTest` pour tester que le champ est bien rempli, et un doctest pour la fonction  `get_max_severity_error`

2022-06-28 15:34 UTC, fchabouis commented
J'ai refait une passe pour tirer au clair les cas "Irrelevant" et "NoError".

Le validateur gtfs ne sort que 4 classes d'erreur, la plus basse étant "Information". Voir [ici](https://github.com/etalab/transport-validator/blob/ed418711c950b47217d4d533abb059bdf673511f/src/issues.rs#L11)

J'ai l'impression qu'avec le temps, 2 termes sont rentrés en concurrence chez nous pour dire qu'il n'y a pas d'erreur : `NoError` et `Irrelevant`. Bon 3 avec "Irrevelant" :P

Je choisis de ne garder que `NoError` qui parait plus explicite. Le validateur du module "Transport.Validators.GTFSTransport" et les fonctions associées n'utiliseront plus jamais dans leurs sorties "Irrelevant", qui va donc être absent de la table de multi_validation.

Pour autant le terme Irrelevant est encore dans la code base à plusieurs endroits : dans des fonctions que j'ai dupliquées et qui s'appliquent à la validation v1, dans le tri des issues par gravité dans le code de la page stat, etc

Je fais une note dans l'issue #2390 pour penser à faire le ménage une fois la validation v1 complètement débranchée.

2022-06-28 15:38 UTC, fchabouis commented on apps/transport/lib/db/resource.ex
> +          %{severity: "NoError", count_errors: 0}
voir commentaire plus bas

2022-06-28 15:38 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
> +              <%= if severity == "NoError" do %>
je l'ai fortement simplifié

2022-06-28 15:41 UTC, fchabouis commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> -    |> Enum.map(fn {key, title} -> {key, %{count: 0, title: title, severity: "Irrelevant"}} end)
je n'ai pas compris pourquoi on voulait avoir toutes les issues, avec un count à 0 et une severity Irrelevant quand elles n'étaient pas présentes dans la sortie du validateur. J'ai l'impression que ça ne servait pas, d'ou la simplification.

2022-06-29 07:33 UTC, AntoineAugusti commented on apps/transport/lib/db/resource.ex
> +          %{severity: "NoError", count_errors: 0}
On peut pas utiliser la nouvelle constante ici ?

2022-06-29 07:33 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/templates/dataset/_resource.html.eex
> +              <%= if severity == "NoError" do %>
Pas d'utilisation de la nouvelle constante ici ?

2022-06-29 07:33 UTC, AntoineAugusti commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +         severity: issues |> List.first() |> Map.get("severity")
Peut-être du `Map.fetch!` pour éviter des erreurs silencieuses ?

2022-06-29 07:33 UTC, AntoineAugusti commented on apps/transport/test/transport/validators/gtfs_transport_validator_test.exs
> +             max_error: "Warning"
Ajouter un test pour pas d'erreurs ? Dans ce cas `max_error` vaut `NoError` ou `nil` ?

2022-06-29 09:23 UTC, fchabouis commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +         severity: issues |> List.first() |> Map.get("severity")
C'est la sortie du validateur Rust, et la severity est obligatoirement présente dans la structure `Issue`, ça peut pas être vide en théorie.
https://github.com/etalab/transport-validator/blob/ed418711c950b47217d4d533abb059bdf673511f/src/issues.rs#L128

2022-06-29 09:29 UTC, fchabouis commented on apps/transport/test/transport/validators/gtfs_transport_validator_test.exs
> +             max_error: "Warning"
ça m'embete de dupliquer tout le test, juste pour tester le comportement de la fonction `get_max_severity_error`, c'est pour ça que j'ai fait le test "global" qui vérifie que le champ est bien rempli et la fonction correctement appelée, et que je teste la fonction `get_max_severity_error` plus en détail avec un doctest.

Si le validateur sort une map d'erreur vide, ça sort "NoError", voir le doctest associé [ici](https://github.com/etalab/transport-site/blob/cd0a28915aadd37f0d89d45b43e8e9828dbd2a00/apps/transport/lib/validators/gtfs_transport_validator.ex#L164)

Est-ce que l'approche te convient ?

2022-06-29 09:47 UTC, AntoineAugusti approved these changes
Bon boulot, ça parait top 🚀

2022-06-29 09:47 UTC, AntoineAugusti commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +  {"Warning", 2}
```suggestion
  iex> count_max_severity(validation_result)
  {"Warning", 2}
  iex> count_max_severity(%{})
  {"NoError", 0}
```
Ajoute un test (suggéré dans https://github.com/etalab/transport-site/pull/2464/files#r909293782), je crois que tu l'avais ajouté dans `count_by_severity`

2022-06-29 09:47 UTC, AntoineAugusti commented on apps/transport/test/transport/validators/gtfs_transport_validator_test.exs
> +             max_error: "Warning"
Ça me parait très bien, tu as déjà pris suffisamment de précautions !

2022-06-29 09:47 UTC, AntoineAugusti commented on apps/transport/lib/validators/gtfs_transport_validator.ex
> +  {"Warning", 2}
Peut-être pas nécessaire comme tu as déjà `get_max_severity_error(%{})`, à ta guise

2022-06-29 09:56 UTC, merged