Map real time stats
etalab/transport-site pull request #2474
Opened 2022-06-23 15:41 UTC by hugoguignardchab

**Modification apportée pour  #2447:**
- Création d'une nouvelle couleur pour les zones possédant le format gtfs rt et siri hachurée vert claire et bleu
- Échange des couleurs entre siri lite et siri pour une meilleure lecture des hachures gtfs rt + siri
- Ajout dans le pop-up d'une ligne indiquant les formats standardisé disponible.

![image](https://user-images.githubusercontent.com/85080846/175336697-d39386f1-62a4-44d1-9155-1a1469357c7a.png)
![image](https://user-images.githubusercontent.com/85080846/175336780-d4d2acf0-6439-4454-b175-a770eae04113.png)

2022-06-27 09:44 UTC, AntoineAugusti commented
@hugoguignardchab @fchabouis Rien à dire sur le code, plus des questions sur les fonctionnalités

2022-06-28 10:29 UTC, hugoguignardchab commented on apps/transport/client/javascripts/map.js
> +            return zoom > 6 ? styles.gtfs_rt_siri.bigStripes : styles.gtfs_rt_siri.smallStripes
Le but ici est de mettre en valeur sur la carte le couple gtfs rt + siri, si les formats gtfs rt + siri sont disponible avec également un autre format la zone vas passer en formats multiples et donc ne pas faire ressortir la présence des format gtfs rt + siri.

2022-06-28 10:30 UTC, hugoguignardchab commented on apps/transport/client/javascripts/map.js
> +        gtfs_rt_siri: { label: 'GTFS RT + SIRI', color: `repeating-linear-gradient(-45deg,blue,blue 3px,${lightGreen} 3px,${lightGreen} 6px)` },
En effet, on n'a pas encore de gtfs rt +siri lite est-il utile de le rajouter dès a présent ?

2022-06-28 10:37 UTC, hugoguignardchab commented on apps/transport/client/javascripts/map.js
>              const text = countOfficial === 1 ? 'Un jeu de données standardisé' : `${countOfficial} jeux de données standardisés`
Du coup peut-être différencier les JDD et les ressources disponibles, ou alors un des deux pour ne pas avoir un surplus d'information.

2022-06-28 10:41 UTC, hugoguignardchab commented on apps/transport/client/javascripts/map.js
> +                formats.push('SIRI Lite')
Je vais mettre ça a jour.

2022-06-28 10:45 UTC, hugoguignardchab commented on apps/transport/client/javascripts/map.js
> +                formats.push('GTFS RT')
je vais corriger ça et le mettre en GTFS-RT.

2022-06-28 11:04 UTC, AntoineAugusti commented on apps/transport/client/javascripts/map.js
> +            return zoom > 6 ? styles.gtfs_rt_siri.bigStripes : styles.gtfs_rt_siri.smallStripes
Yes, bien compris ceci. Je ne voyais pas de différence entre les petits et les gros traits.

2022-06-28 11:04 UTC, AntoineAugusti commented on apps/transport/client/javascripts/map.js
> +        gtfs_rt_siri: { label: 'GTFS RT + SIRI', color: `repeating-linear-gradient(-45deg,blue,blue 3px,${lightGreen} 3px,${lightGreen} 6px)` },
On peut surement attendre un peu, indique-le dans l'issue.

2022-06-28 11:05 UTC, AntoineAugusti commented
@hugoguignardchab Tu peux redemander une review dès que tu auras traité les commentaires en allant tout en haut à droite de la page de PR, section "Reviewers" 👌

2022-06-28 12:31 UTC, hugoguignardchab commented on apps/transport/client/javascripts/map.js
> +            return zoom > 6 ? styles.gtfs_rt_siri.bigStripes : styles.gtfs_rt_siri.smallStripes
Le changement s'effectue lors du zoom. Les grosses bandes ne sont pas bien visibles dézoomer et les petites ne rende pas bien zoomer. C'est ce que Francis avait fait pour les hachure des AOM.

2022-06-28 14:20 UTC, AntoineAugusti requested changes
Peux-tu uniformiser la casse des formats ?

Attendu :
- GTFS-RT
- SIRI
- SIRI Lite

dans le code JavaScript et modifier ce template HTML (qui n'a pas été modifié, mais comme c'est juste à coté, [_boy scout rule_](https://www.stepsize.com/blog/how-to-be-an-effective-boy-girl-scout-engineer) https://github.com/etalab/transport-site/blob/61611d9293b148cb0495d7f9e19e6fd80f679d4a/apps/transport/lib/transport_web/templates/stats/index.html.eex#L188 (demandé dans [ce commentaire](https://github.com/etalab/transport-site/pull/2474#discussion_r907174072)).

2022-06-29 07:35 UTC, AntoineAugusti approved these changes
Me parait bien !

Avant de merger, quelques choses à considérer/faire :
- voir le texte qui parle de jeux de données alors que ça compte des ressources https://github.com/etalab/transport-site/pull/2474/files#r908323604
- tenir à jour l'issue avec les décisions prises https://github.com/etalab/transport-site/pull/2474/files#r908345867

Bravo pour le boulot 👏 🗺️

2022-06-29 11:18 UTC, hugoguignardchab commented
J'ai changé le " jeu de données standardisé" en "ressource standardisée " car en effet le compteur est sur le nombre de ressource. De plus, j'ai ajouté l'affichage du nombre de ressource non standardisé.

2022-06-29 11:35 UTC, AntoineAugusti commented
@hugoguignardchab Top ! J'avais approuvé la PR avant, tu peux merger à ta convenance.

Bravo à nouveau 💪

2022-06-29 12:05 UTC, merged