community ressources section
etalab/transport-site pull request #2564
Opened 2022-08-05 08:53 UTC by hugoguignardchab

Création d'une sections "Ressources communautaires" dans la liste déroulante à gauche des jeux de données
https://github.com/etalab/transport-site/issues/2559
![image](https://user-images.githubusercontent.com/85080846/183040738-508e4d35-aed6-44eb-b514-a3f567fb75d5.png)
seconde pr car erreur avec mix dialyzer
première pr :  #2560

2022-08-05 09:03 UTC, hugoguignardchab commented
Il y avait une erreur a cause de la condition " <%= unless community_resources(@dataset) == 0 do %> "
Je l'ai donc enlever, la section ressource communautaire sera toujours présente.

2022-08-11 05:47 UTC, thbar requested changes
Quelques petits changements que je vais gérer moi-même en l'absence de @hugoguignardchab (merci pour ta PR !)

2022-08-11 05:47 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/details.html.heex
> +      </div>
J'ai été vérifier si on risquait d'avoir un lien ici qui pointe vers une section inexistante, mais la section apparaît toujours (voir copie d'écran) donc ça me semble bon a priori :

<img width="798" alt="CleanShot 2022-08-11 at 07 43 56@2x" src="https://user-images.githubusercontent.com/10141/184071160-ad0534a7-c8a9-455c-986c-161e95dc621e.png">

2022-08-11 05:47 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/_community_resources.html.eex
> +<section class="dataset__resources white" id="Community-resources">
On utilise plutôt des ids en minuscules, je vais modifier ce point:

```suggestion
<section class="dataset__resources white" id="community-resources">
```

2022-08-11 05:47 UTC, thbar commented on apps/transport/lib/transport_web/templates/dataset/details.html.heex
> +        <a href="#Community-resources"><%= dgettext("page-dataset-details", "Community resources") %></a>
```suggestion
        <a href="#community-resources"><%= dgettext("page-dataset-details", "Community resources") %></a>
```

2022-08-11 05:48 UTC, thbar commented
> Il y avait une erreur a cause de la condition " <%= unless community_resources(@dataset) == 0 do %> "
> Je l'ai donc enlever, la section ressource communautaire sera toujours présente.

À la réflexion je pense qu'il vaudrait mieux remettre ce code en place si il était déjà là, ça sera plus solide.

On va voir comment le réintégrer et quelle était l'erreur.

2022-08-11 06:10 UTC, thbar commented
J'ai été reproduire l'erreur que tu avais @hugoguignardchab sur l'autre PR:

https://github.com/etalab/transport-site/pull/2560/files#diff-7cda7f861e4c1f6dbda1cea3d9c427d3a7e8f2e364b2048b55b99922779a85ffR32

Voici l'explication pour ta gouverne : avec `unless community_resources(@dataset) == 0`, Dialyzer se plaignait que l'égalité ne peut jamais arriver:

```
The test [
  %DB.Resource{ .... }
] == 0 can never evaluate to 'true'.
```

C'est en fait car la liste retournée est une liste de ressources, et non un count, et donc ça ne peut jamais être vérifié (le typage est incorrect).

Il aurait fallu pour réussir créer une méthode qui fait ce même count dans la même veine que:

https://github.com/etalab/transport-site/blob/38dcc40bddd03bc1307289b10793a249a68a7098/apps/transport/lib/transport_web/views/dataset_view.ex#L27-L30

Cela étant dit, comme tu l'as évoqué ça me paraît suffisant de conserver le lien vers la section tout le temps, car il y a un peu de texte incitatif, et donc ça fait sens.

Maintenant que j'ai compris le tout, je vais pouvoir approuver la PR.

2022-08-11 06:11 UTC, thbar approved these changes
C'est tout bon à présent, j'envoie.

Merci @hugoguignardchab pour le ground-work !

2022-08-11 06:11 UTC, merged

2022-08-16 15:00 UTC, hugoguignardchab commented
merci de l'aide !