Ajout bouton pour valider immédiatement le GBFS
etalab/transport-site pull request #2604
Opened 2022-08-29 08:56 UTC by AntoineAugusti

En une capture d'écran :

![image](https://user-images.githubusercontent.com/295709/187164186-dcfff26e-c55d-48ff-9cea-275fda656de7.png)

Ceci est déjà fait pour les GTFS-RT.

2022-08-30 10:31 UTC, fchabouis requested changes
Ca serait bien de faire apparaitre le bouton aussi quand aucune validation n'est présente.
S'il n'y a pas de validation, on ne passe même pas dans le template https://github.com/etalab/transport-site/blob/eb448a44ceafe54d0ba2e31d605fd303443eef84/apps/transport/lib/transport_web/templates/resource/_validation_report.html.heex#L15

2022-08-30 11:58 UTC, AntoineAugusti commented
@fchabouis C'est actuellement non lié, ce bouton lance une validation à la demande alors que les validations affichées ici sont planifiées.

Si une validation à la demande est lancée elle ne sera pas affichée ici.

Il y a pas mal d'autres considérations si on souhaite faire ça, ça me parait hors scope.

2022-08-30 11:58 UTC, AntoineAugusti commented
@fchabouis Ah, ou alors uniquement le bouton de validation à la demande si rien n'a été exécuté ?

2022-08-30 12:00 UTC, fchabouis commented
En local j'avais des resources GBFS pour lesquelles la validation n'avait pas tourné, et pour ces jeux le bouton de validation à la demande que tu ajoutes n'apparait pas, alors qu'il n'y a pas de raison à priori.

2022-08-30 12:59 UTC, AntoineAugusti commented
@fchabouis J'ai mis les boutons de validation à la demande pour GBFS et GTFS-RT, y compris quand aucune validation n'est disponible ! J'ai extrait des partials.

2022-09-01 14:23 UTC, AntoineAugusti commented
@fchabouis J'ai bien pris en compte ta demande

2022-09-01 14:38 UTC, fchabouis commented on apps/transport/lib/transport_web/templates/resource/_validation_report.html.heex
>      <%= dgettext("validations", "No validation available") %>
```suggestion
    <div>
      <%= dgettext("validations", "No validation available") %>
    </div>
```

Pour éviter 
![image](https://user-images.githubusercontent.com/15341118/187941636-71951d50-df05-4501-bf9e-be5bc46d78e4.png)

2022-09-02 10:57 UTC, AntoineAugusti commented
@fchabouis J'ai intégré ta suggestion 🙏

2022-09-05 14:37 UTC, fchabouis approved these changes

2022-09-05 14:37 UTC, merged