Intégration des parkings relais sur la carte d'exploration
etalab/transport-site pull request #2723
Opened 2022-10-18 07:18 UTC by AntoineAugusti

2022-10-20 15:20 UTC, fchabouis requested changes

2022-10-20 15:20 UTC, fchabouis commented on apps/transport/priv/gettext/en/LC_MESSAGES/explore.po
> +msgstr "Park and rike data coming from the National parking database %{link}"
```suggestion
msgstr "Park and ride data coming from the national parking database %{link}"
```

2022-10-21 07:54 UTC, fchabouis approved these changes
:+1:

2022-10-31 13:16 UTC, AntoineAugusti commented
On va attendre avant de 🚢 @etalab/transport-bizdev doivent nous indiquer quelle source utiliser pour les parkings relais

2022-12-01 10:41 UTC, cyrilmorin commented
OK pour utiliser la source [actuelle](https://transport.data.gouv.fr/datasets/base-nationale-des-parkings-relais-en-cours-de-consolidation à ce stade et afficher le filtre et du coup en faisant référence dans la description à la Base national des parking relais (vs la BNLS) car l'objectif était de décorréler les 2 jeux pour simplifier la vie des producteurs

![image](https://user-images.githubusercontent.com/116101828/205031697-cd4154f1-a7f9-4d29-884c-6573a7e24746.png)

2022-12-01 11:03 UTC, merged