Ressources historisées : prendre la periode de validité dans les métadonnées
etalab/transport-site pull request #2862
Opened 2022-12-16 11:05 UTC by fchabouis

suite de #2810 pour l'affichage des dates de validité dans la section "ressources historisées"

2022-12-16 12:20 UTC, AntoineAugusti requested changes

2022-12-16 12:20 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/views/dataset_view.ex
> +  def has_validity_period?(%DB.ResourceHistory{validations: [%{metadata: %{metadata: %{} = metadata}}]}) do
Peut-être utiliser `validity_period` maintenant ?

2022-12-28 13:41 UTC, fchabouis commented on apps/transport/lib/transport/history_fetcher.ex
> -    |> where([_rh, r], not is_nil(r.id) or fragment("cast(payload->>'dataset_id' as bigint) = ?", ^dataset_id))
yes je fais ça, merci

2022-12-28 13:50 UTC, fchabouis commented on apps/transport/lib/transport_web/views/dataset_view.ex
> +  def has_validity_period?(%DB.ResourceHistory{validations: [%{metadata: %{metadata: %{} = metadata}}]}) do
ok

2022-12-28 14:02 UTC, AntoineAugusti approved these changes
Merci pour le nettoyage !

2022-12-28 14:21 UTC, merged