Suppression parent_dataset pour les AOMs et utilisation des responsables légaux
etalab/transport-site pull request #3250
Opened 2023-06-23 07:52 UTC by AntoineAugusti

2023-06-23 13:37 UTC, AntoineAugusti commented on apps/transport/lib/db/dataset.ex
> +  def order_datasets(datasets, %{"aom" => aom_id}) do
En cas de recherche par AOM on met les JDD rattachés directement à l'AOM en premier, les agrégats ensuite

2023-06-23 13:37 UTC, AntoineAugusti commented on apps/transport/priv/repo/migrations/20230623121709_aom_remove_parent_dataset_id.exs
> +    END IF;
Cette partie a été modifiée

2023-06-28 16:12 UTC, fchabouis commented on apps/transport/lib/db/dataset.ex
> +    aom_id =
Je propose cette version alternative de la fonction :
```elixir
  defp filter_by_aom(query, %{"aom" => aom_id}) do
    aom_id = String.to_integer(aom_id)
    query
    |> join(:left, [dataset: d], aom in assoc(d, :legal_owners_aom), on: aom.id == ^aom_id, as: :aom)
    |> where([dataset: d, aom: aom], d.aom_id == ^aom_id or aom.id == ^aom_id)
  end
```

Explications:
* si `aom_id` vaut nil après avoir été parsée par `Integer.parse`, on va avoir une condition `where: a.aom_id == nil,`, ce qui est interdit avec Ecto.
![image](https://github.com/etalab/transport-site/assets/15341118/d78a7245-cf57-4587-b3f4-2efeb50ede06)
* il n'est normalement jamais nécessaire de faire appel aux tables intermédiaires des relations many-to-many. Voir la doc à ce [sujet](https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3-using-ecto-assoc-2). "One of the benefits of using many_to_many is that Ecto will avoid loading the intermediate whenever possible, making your queries more efficient. For this reason, developers should not refer to the join table of many_to_many in queries."
* `String.to_integer(aom_id)` va crasher en cas de problème, mais ça ne pose de problème car le cas est déjà géré ailleurs.
![image](https://github.com/etalab/transport-site/assets/15341118/1e357c80-4d1d-4aba-809c-74edd1150f9c)

2023-06-28 16:13 UTC, fchabouis commented
j'ai pas eu le temps de tout relire, je continuerai demain matin.

2023-06-29 07:36 UTC, fchabouis requested changes
J'ai bien lu les premiers fichiers, un peu plus rapidement le reste. C'est un beau travail, félicitations !
Ma seule remarque concerne la référence dans le code à la table intermédiaire qui n'est normalement pas nécessaire avec un `many_to_many` et que la doc recommande d'éviter. Je pense que ça serait bien de réécrire les queries avec des `assoc`, ça fait un code plus lisible je trouve et ça évitera que de futurs développeurs aient des exemples sous les yeux de requêtes qui utilisent des tables intermédiaires via des `fragment`, surtout que ce type de relations `many_to_many` vont peut-être être de plus en plus nombreuses dans le code à l'avenir. Je sais que ça représente du boulot de réécrire, ça dépend de ton niveau d'énergie sur la question !

2023-06-29 07:36 UTC, fchabouis commented on apps/transport/lib/db/dataset.ex
> +    end
```suggestion
    aom_id = String.to_integer(aom_id)

    order_by(datasets,
      desc: fragment("case when aom_id = ? then 1 else 0 end", ^aom_id),
      desc: fragment("coalesce(population, 0)"),
      asc: :custom_title
    )
```

Je pense qu'ici aussi on peut se passer de gérer des erreurs de parsing

2023-06-29 07:36 UTC, fchabouis commented on apps/transport/lib/transport/stats_handler.ex
> +                left join dataset_aom_legal_owner a on a.dataset_id = d.id and a.aom_id = ?
On peut normalement se passer d'utiliser `dataset_aom_legal_owner`

```elixir
DB.Dataset.base_query() 
|> join(:left, [d], aom in assoc(d, :legal_owners_aom), on: aom.id == ^aom_id) 
|> where([d, aom], d.aom_id == ^aom_id or aom.id == ^aom_id) 
|> DB.Repo.aggregate(:count)
```

2023-06-29 07:36 UTC, fchabouis commented on apps/transport/lib/transport/stats_handler.ex
> +      on: dataset.id == legal_owner.dataset_id or dataset.aom_id == aom.id
Ici aussi on doit pouvoir utiliser `assoc`

2023-06-29 07:36 UTC, fchabouis commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
> +  defmacro count_aom_types(aom_id, type, include_aggregates: true) do
je découvre qu'on a des macros dans le code, il était temps :P

2023-06-29 07:36 UTC, fchabouis commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
> +        left join dataset_aom_legal_owner a on a.dataset_id = d.id and a.aom_id = ?
Je me passerai bien de la table intérmédiaire ici aussi.

2023-06-29 07:36 UTC, fchabouis commented on apps/transport/lib/transport_web/api/controllers/stats_controller.ex
> +          left join dataset_aom_legal_owner a on a.dataset_id = d.id and a.aom_id = ?
idem

2023-06-29 12:36 UTC, AntoineAugusti commented
@fchabouis J'ai supprimé beaucoup d'utilisations de la table directement dans le dernier commit. J'ai laissé 2 cas, qui sont dans des macros. J'ai ouvert une issue de dette technique pour ne pas l'oublier et tenter de le faire un jour.

2023-07-03 08:18 UTC, thbar approved these changes
J'ai refait un tour et un peu de test en local (un endroit où je me demandais si on avait un N+1), ça me semble tout bon. Super boulot c'est un beau morceau.

2023-07-03 08:27 UTC, merged