ResourceUnavailableNotificationJob : améliore le contenu
etalab/transport-site pull request #3316
Opened 2023-07-13 09:25 UTC by AntoineAugusti

Améliore le contenu de la notification envoyée aux producteurs lorsque l'on détecte des ressources indisponibles depuis plus de 6h.

Détecte quand une ressource hébergée sur datagouv a été supprimée (est source de l'indisponibilité) et que le producteur a créé une nouvelle ressource dans la foulée. Dans ce cas, on indique qu'il faut remplacer la ressource existante et on met un lien vers la documentation.

2023-07-17 08:13 UTC, vdegove reviewed
Côté code, ça m’a l’air ok. Par contre, je pense que la formulation pour l’utilisateur peut être améliorée, soit dans l’email, soit dans la doc. On explique à l’utilisateur qu’il a fait une erreur : ce qui n’est pas clair, c’est comment la corriger, et si il doit la corriger ou si on lui dit ça pour la prochaine fois. On lui envoie une doc qui explique comment tout faire bien depuis le début. Si on attend qu’il corrige cette erreur cette fois-ci, il faudrait lui dire comment, par exemple :
1. Mettez à jour l’ancienne ressource avec les nouvelles données
2. Supprimez la ressource nouvellement crée qui sera alors en doublon.

Est-ce qu’on a une issue pour alerter sur le problème de double resource dès l’upload des données ? Ou créer un point d’action qui permet de faire le remplacement automatiquement (met à jour l’ancienne resource, supprime la nouvelle) ?

2023-07-17 08:21 UTC, AntoineAugusti commented
@vdegove Tu as des suggestions d'adaptation du texte ? N'hésite pas à en faire cc @etalab/transport-bizdev par ailleurs.

Pour faire être plus proactif c'est délicat :
- si la maj a été réalisée depuis l'espace producteur on devrait orienter pas mal (indiquer de remplacer plutôt d'en faire une nouvelle ressource)
- si c'est réalisé depuis l'admin datagouv on ne peut rien faire : on n'a pas la main sur l'UI et on ne sait pas en temps réel que cette action a été faites (on le saura lors du prochain import)
- on ne peut pas non plus bloquer l'ajout d'une seconde ressource GTFS, c'est parfois légitime de passer de 1 GTFS dans le JDD à 2 fichiers

Si tu as d'autres idées pour améliorer les choses n'hésite pas ! On pourra traiter ça dans d'autres tickets

2023-07-17 08:52 UTC, vdegove commented
Ok ! Pour le texte de l’email, les bizdevs seront probablement mieux placés que moi pour faire un mode d’emploi actionnable qui permette de résoudre l’erreur, mais c’est probablement de cet ordre d’idée là : suivre le tuto pour mettre à jour l’ancienne resource, puis supprimer la nouvelle (et je pense que c’est mieux d’être explicite là dessus si c’est bien ce qu’on attend du producteur).

2023-07-17 09:07 UTC, AntoineAugusti commented
@etalab/transport-bizdev Le texte envoyé est celui-ci https://github.com/etalab/transport-site/pull/3316/files#diff-af87b1aef8ca26ca9c703b4d21bd8d6af7d3ed9babe5240cdb0aed32b3b5f45e

2023-07-18 10:16 UTC, vdegove requested changes
Mes suggestions de wording

2023-07-18 10:16 UTC, vdegove commented on apps/transport/lib/transport_web/templates/email/resource_unavailable.html.md
> +Il semble que vous ayez supprimé et créé une nouvelle ressource. Lors de la mise à jour de vos données, privilégiez le remplacement de fichiers. Retrouvez la procédure pas à pas [sur notre documentat
```suggestion
Il semble que vous ayez supprimé et créé une nouvelle ressource. Lors de la mise à jour de vos données, remplacez plutôt le fichier au sein de la resource existante. Retrouvez la procédure pas à pas [sur notre documentation](https://doc.transport.data.gouv.fr/producteurs/mettre-a-jour-des-donnees).
```

2023-07-18 10:16 UTC, vdegove commented on apps/transport/lib/transport_web/templates/email/resource_unavailable.html.md
> +1. Mettez à jour l’ancienne ressource avec les nouvelles données ;
```suggestion
Pour corriger le problème pour cette fois-ci  :
1. Mettez à jour l’ancienne ressource avec les nouvelles données en [suivant notre documentation](https://doc.transport.data.gouv.fr/producteurs/mettre-a-jour-des-donnees) ;
```

2023-07-18 10:20 UTC, AntoineAugusti commented on apps/transport/test/transport/jobs/resource_unavailable_notification_job_test.exs
> +               "Il semble que vous ayez supprimé et créé une nouvelle ressource. Lors de la mise à jour de vos données, privilégiez le remplacement de fichiers."
```suggestion
               "Il semble que vous ayez supprimé et créé une nouvelle ressource. Lors de la mise à jour de vos données, remplacez plutôt le fichier au sein de la ressource existante."
```

2023-07-18 10:23 UTC, AntoineAugusti commented
@vdegove Merci pour l'amélioration du contenu ! 🙏 🗒️

2023-07-18 14:30 UTC, vdegove approved these changes

2023-07-18 14:37 UTC, merged