Consolidation BNLC : détecte les erreurs lors du décodage d'un CSV
etalab/transport-site pull request #3586
Opened 2023-11-08 06:26 UTC by AntoineAugusti

2023-11-08 08:21 UTC, AntoineAugusti commented
Je suis tombé sur un problème avec [csv](https://hex.pm/packages/csv) dans mon premier commit, ça m'a pris du temps de remonter le problème https://github.com/beatrichartz/csv/issues/125

2023-11-08 08:25 UTC, AntoineAugusti commented on apps/transport/lib/jobs/consolidate_bnlc_job.ex
> +  end
C'est du [boy scout](https://biratkirat.medium.com/step-8-the-boy-scout-rule-robert-c-martin-uncle-bob-9ac839778385) ceci et le renommage de `:validation_error` vers `:validator_unavailable_error`

2023-11-08 13:41 UTC, AntoineAugusti commented
@AurelienC Avec ce changement tu pourras conserver Châlon dans `datasets.csv` et ce sera indiqué qu'il y a bien une erreur lors du décodage.

2023-11-10 12:04 UTC, vdegove requested changes
Ça me semble bien à part une micro typo dans un commentaire et une question de nommage.

Si je comprends bien, vu ton commentaire sur CSV.decode!, à la base, tu voulais gérer ça directement dans consolidate_resources (la partie append other valid resources) ? Ou pas ? En tout cas ça fait deux passes de décodage de CSV des resources d’origine, une pour vérifier la bonne conformité, l’autre pour append au fichier consolidé, donc ça rajoute un peu de temps de traitement, mais j’imagine que c’est mineur et qu’il n’y a pas de solution en une passe ?

2023-11-10 13:42 UTC, AntoineAugusti commented on apps/transport/lib/jobs/consolidate_bnlc_job.ex
> +  defp decode_csv(body, {dataset_details, %{@separator_key => separator, @download_path_key => path} = resource}) do
J'ai renommé en `check_can_decode_csv`

2023-11-10 13:48 UTC, AntoineAugusti commented
@vdegove Merci pour ta review, j'ai traité tes commentaires !

> Si je comprends bien, vu ton commentaire sur CSV.decode!, à la base, tu voulais gérer ça directement dans consolidate_resources (la partie append other valid resources) ?

Non je voulais traiter avant `consolidate_resources`. Cette fonction prend normalement des choses qui sont conformes et validées et peut ensuite dérouler (lire des fichiers valides, déjà présents sur le disque, bon format etc).

https://github.com/etalab/transport-site/blob/54bc47107a61f296b723473634ad70c38693fa8f/apps/transport/lib/jobs/consolidate_bnlc_job.ex#L66-L76

> En tout cas ça fait deux passes de décodage de CSV des resources d’origine, une pour vérifier la bonne conformité, l’autre pour append au fichier consolidé, donc ça rajoute un peu de temps de traitement, mais j’imagine que c’est mineur et qu’il n’y a pas de solution en une passe ?

En fait ce n'était pas prévu que cette erreur arrive. Aurélien et moi avons été surpris qu'une telle erreur (unescaped double quotes in a value) passe le validateur TableSchema et on a eu un crash inattendu dans `CSV.decode!` dans `consolidate_resources`. On a donc cherché à détecter cette erreur potentielle en amont.

Je pense qu'il est possible d'avoir un seul décodage, mais pas sûr que ça vaille le coup du refactor car :
- `CSV.decode` est fait en streaming et on veut minimiser l'usage mémoire de manière générale (on aurait pu passer tous les contenus de fichiers en mémoire mais bof)
- la BNLC va faire < 10k lignes ce qui n'est pas énorme si on doit décoder 2 fois le tout en CSV
- le temps d'exécution, tant qu'il est inférieur à ~30s est tout à fait acceptable au vu du travail réaliser : consolider un fichier d'une base nationale. Exécution 1 fois par jour en rythme de production, moins actuellement. On est très loin de ce temps actuellement, on est sur du 5s de mémoire

2023-11-10 16:04 UTC, vdegove approved these changes

2023-11-10 16:10 UTC, merged