ConsolidateBNLCJob : répare décodage fichier BNLC
etalab/transport-site pull request #3598
Opened 2023-11-14 12:41 UTC by AntoineAugusti

En lien avec #3419

Répare un bug introduit en voulant traiter https://github.com/etalab/transport-site/pull/3563#discussion_r1375925884

## Symptome

En consolidant la BNLC, avec le code précédent on ignore la colonne `id_lieu` dans `bnlc_csv_headers/0`. Par la suite, la ligne `|> CSV.decode!(field_transform: &String.trim/1, headers: bnlc_headers)` fait qu'on utilise les header qu'on passe (en ignorant ceux présents en ligne 1) pour le fichier [`bnlc-.csv`](https://github.com/etalab/transport-base-nationale-covoiturage/blob/main/bnlc-.csv). On a ainsi un décalage des colonnes qui [se répercute dans le fichier consolidé](https://app.frontapp.com/open/cnv_zqmgj2u?key=qqu9ccVAHfhUVyjfOoxmlYSWDCHOcfo7), uniquement pour la BNLC sur GitHub et pas des fichiers provenant de data.gouv.fr.

## Correction

On arrête d'ignorer `id_lieu` dans `bnlc_csv_headers/0` et on s'assure que le header du fichier consolidé contient `id_lieu + ($bnlc_headers - id_lieu)`.

2023-11-14 12:42 UTC, AntoineAugusti commented on apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
> +        Very,Much,So,4,21231,6
Il manquait précédemment la colonne `id_lieu` dans les tests pour mettre en évidence le bug rencontré.

2023-11-14 14:53 UTC, AntoineAugusti commented
@vdegove Je pense que tu es le mieux pour review cette PR comme tu as revu la précédente. @AurelienC, ceci corrige le bug constaté ce matin ensemble

2023-11-16 09:12 UTC, vdegove requested changes
Petite demande (pas directement reliée au bug résolu) : est-ce que tu peux aussi mettre dans les exemples de resources à consolider une resource où le producteur a mis par lui-même une colonne id_lieu, pour mettre en évidence que cette colonne va être remplacée ? Je sais, le test avec extra_col fait au fond ça, mais c’est bien d’être explicite sur la dynamique sur cette colonne id_lieu (= de base, le producteur n’est pas sensé la mettre mais si jamais c’est le cas, on la retire et on l’écrase).

2023-11-16 09:12 UTC, vdegove commented on apps/transport/lib/jobs/consolidate_bnlc_job.ex
> +    final_headers = ["id_lieu"] ++ Enum.reject(bnlc_headers, &(&1 == "id_lieu"))
Est-ce que c’est vraiment la peine de faire ça ? reject + le remettre à nouveau ? Est-ce que on peut pas juste prendre bnlc_headers sans retirer puis remettre vu que le cas où la colonne n’y est pas présente ne va plus survenir ?

2023-11-16 09:17 UTC, AntoineAugusti commented on apps/transport/lib/jobs/consolidate_bnlc_job.ex
> +    final_headers = ["id_lieu"] ++ Enum.reject(bnlc_headers, &(&1 == "id_lieu"))
Actuellement si on ne fait pas ça on aurait 2 fois `id_lieu` car dans la version 0.2.8 il y a bien `id_lieu` dans le schéma donc ce serait présent dans `bnlc_headers`

2023-11-16 09:28 UTC, vdegove approved these changes

2023-11-16 09:33 UTC, merged

2023-11-16 09:53 UTC, AntoineAugusti commented
@AurelienC Le fix est en prod, tu peux vérifier que le problème est bien corrigé ?