Job consolidation BNLC : permet de remplacer le fichier sur datagouv
etalab/transport-site pull request #3607
Opened 2023-11-17 09:50 UTC by AntoineAugusti

En lien avec https://github.com/etalab/transport-site/issues/3419

Adapte le job pour ajouter la possibilité de remplacer le fichier sur data.gouv.fr. C'est similaire à ce qui est fait dans la consolidation ZFE (`ConsolidateLEZsJob`).

Je fais la partie job dans cette PR, je ferai une PR supplémentaire pour ajouter un bouton correspondant à ce nouveau `perform` dans le backoffice.

2023-11-17 09:53 UTC, AntoineAugusti commented on config/runtime.exs
>          }
Faut vérifier les identifiants https://www.data.gouv.fr/api/1/datasets/base-nationale-des-lieux-de-covoiturage/

2023-11-17 09:53 UTC, AntoineAugusti commented on apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
> +
À partir de là j'ai extrait des méthodes que j'appelais plusieurs fois

2023-11-17 09:53 UTC, AntoineAugusti commented on apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
> +  test "perform and update file on data.gouv.fr" do
Les 2 nouveaux tests

2023-11-17 14:17 UTC, AurelienC approved these changes

2023-11-20 10:18 UTC, thbar commented
@vdegove je te laisse la main sur celle là !

2023-11-20 10:56 UTC, vdegove requested changes
Merci pour le refactor dans les tests, c’est une PR utile à lire ! Je mets «request changes» pour que tu puisses répondre à mes petites questions sans que ça merge, mais sinon c’est prêt à être mergé.

2023-11-20 10:56 UTC, vdegove commented on config/config.exs
> +      dataset_id: "5d6eaffc8b4c417cdc452ac3",
Pourquoi y a t’il besoin de les mettre à la fois dans config.exs et runtime.exs ?

2023-11-20 10:56 UTC, vdegove commented on apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
> +    expect_datagouv_http_call()
Trop bien toutes les requêtes extraites pour simplifier la lisibilité des tests :) Pour cette-ci tu pourrais rajouter un nom pour rappeler l’utilité de l’appel à datagouv ? Genre `expect_datagouv_post_consolidated_http_call` ?

2023-11-20 10:56 UTC, vdegove commented on apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
> +      expect_s3_upload()
Mémoire de poisson rouge alors que j’ai tout reviewé , je me rappelle plus pourquoi on devait faire un appel à s3… J’avais l’impression qu’on faisait tout en local sur le /tmp du worker, puis (nouvelle partie) on uploade à la fin sur datagouv.

Ça me fait dire qu’il est peut-être temps de remplacer le « Need to write some documentation » en expliquant le workflow : téléchargement des resources séparées depuis la liste des resources, check du schéma, etc, etc (et où et comment techniquement).

2023-11-20 10:56 UTC, vdegove commented on apps/transport/test/transport/jobs/consolidate_bnlc_job_test.exs
> +    assert :ok == perform_job(ConsolidateBNLCJob, %{"action" => "datagouv_update"})
Note pour moi même, je me rappelais plus, mais perform_job vient de Oban.Testing https://hexdocs.pm/oban/Oban.Testing.html#perform_job/3

2023-11-20 10:56 UTC, vdegove commented on apps/transport/lib/jobs/consolidate_bnlc_job.ex
> +  def perform(%Oban.Job{id: job_id, args: %{"action" => "datagouv_update"}}) do
Du coup le sous-entendu de ça c’est que l’action «par défaut» c’est juste envoyer l’email, et qu’il faut passer un argument spécial au job Oban pour que ça uploade aussi sur Datagouv, comme ça :

`%{"action" => "datagouv_update"} |> Transport.Jobs.ConsolidateBNLCJob.new() |> Oban.insert()`

2023-11-20 12:13 UTC, AntoineAugusti commented
@vdegove J'ai pris en compte tes commentaires, merci ! Le fichier consolidé est mis sur S3 car il y a un lien mis dans le rapport de consolidation pour le télécharger, avec un job qui est scheduled 1 semaine plus tard pour le supprimer.

2023-11-20 13:30 UTC, vdegove approved these changes

2023-11-20 13:37 UTC, merged