Calcule et stocke un score de conformité
etalab/transport-site pull request #3622
Opened 2023-11-23 09:49 UTC by AntoineAugusti

Fixes #3579

PR précédente faisant quelque chose de similaire #3333

Calcule et stocke un nouveau score d'un JDD, le score de conformité.

## Périmètre du score

- concerne les ressources qui sont actuellement validées (GTFS, GBFS et ressources avec un schéma associé)
  - ignore les ressources GTFS-RT
  - pour GTFS ne s'intéresser qu'aux erreurs de type `Error` et `Fatal` (comme ce qui est fait pour la notification d'erreurs de validation)
- le score vaut 0 (si au moins une erreur en GBFS/schémas et si `max_error` est `Error` ou `Fatal` en GTFS) ou 1 sinon
- pour un JDD, faire la moyenne des scores des ressources prises en compte

2023-11-23 10:03 UTC, AntoineAugusti commented on apps/transport/lib/jobs/dataset_quality_score.ex
> +    exp_smoothing(previous_score, today_score, 0.95)
Score différent des autres topics, choisi ici https://github.com/etalab/transport-site/issues/3579#issuecomment-1798332164

2023-11-23 10:03 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/templates/dataset/_dataset_scores.html.heex
Un petit refactor de ce fichier pour éviter 3 blocs dupliqués

2023-11-23 17:43 UTC, AntoineAugusti commented
@vdegove Dispo si tu veux en discuter 😉

2023-11-24 10:02 UTC, vdegove requested changes
RAS ou des détails, ça profite de la plomberie déjà en place (merci pour les petits refactos), du coup l’essentiel de la fonctionnalité c’est dans Transport.Jobs.DatasetComplianceScore.current_dataset_compliance/1 et Transport.Jobs.DatasetComplianceScore.resource_compliance/2

À la relecture, j’ai eu un peu de mal à me replonger dans le module `Transport.Jobs.DatasetQualityScore` et voir comment les fonctions dans les sous-modules de qualité étaient appelés. Est-ce que ça ne vaudrait pas la peine d’essayer de simplifier encore ça et refactor ?

Si on regarde :
`Transport.Jobs.DatasetQualityScore.perform/1` appelle `Transport.Jobs.DatasetComplianceScore/save_compliance_score/1`, un one liner, qui appelle à son tour `Transport.Jobs.DatasetQualityScore.save_dataset_score/2`, qui va appeler `Transport.Jobs.DatasetQualityScore.dataset_score/2`, qui lui même (à travers `compute_fn_for_topic/1`) va enfin appeler `Transport.Jobs.DatasetComplianceScore.current_dataset_compliance/1`.

En fait, on peut éviter un aller-retour entre les deux modules en supprimant les fonctions one liner `Transport.Jobs.DatasetComplianceScore/save_compliance_score/1`, qu’en penses-tu ?

2023-11-24 10:48 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/templates/dataset/_dataset_scores.html.heex
> +        Score <%= description %> : <%= DB.DatasetScore.score_for_humans(score) %>
À traiter à part, ça n'a pas été abordé. Il y a un gros chantier UI/explications à mener, pas dans cette PR.

On abandonnera cette vue qui est dédiée aux administrations de toute évidence.

2023-11-24 10:50 UTC, AntoineAugusti commented on apps/transport/test/transport/jobs/dataset_quality_score_test.exs
> +    end
Ok, j'ajoute

2023-11-24 10:50 UTC, AntoineAugusti commented on apps/transport/test/transport/jobs/dataset_quality_score_test.exs
> +        topic: Enum.random(topics),
Hmm, ça se questionne. C'est pour "prouver" qu'on peut mettre n'importe quel topic vu la nature du test (on ne remonte pas trop loin dans le passé).

Sinon perdre une valeur, mais c'est arbitraire.

2023-11-24 11:06 UTC, AntoineAugusti commented on apps/transport/lib/jobs/dataset_quality_score.ex
> +  def resource_compliance({resource_id, [%DB.MultiValidation{result: %{"has_errors" => has_errors} = result}]}) do
Ajouté, ça rajoute pas mal de bruit. À voir !

2023-11-24 11:06 UTC, AntoineAugusti commented on apps/transport/lib/jobs/dataset_quality_score.ex
> +      |> DB.MultiValidation.dataset_latest_validation(@validators)
Yep

2023-11-24 11:07 UTC, AntoineAugusti commented
@vdegove J'ai bien pris en compte tes commentaires, merci 🙏

2023-11-24 13:21 UTC, vdegove commented on apps/transport/lib/jobs/dataset_quality_score.ex
> +                              )
Ça marche ou pas de faire des calculs dans des module attributes à partir de d’autres module attributes ?

```
@validators_with_has_errors =  [Transport.Validators.TableSchema, Transport.Validators.EXJSONSchema, Transport.Validators.GBFSValidator]
@gtfs_validator = Transport.Validators.GTFSTransport
@validators = @validators_with_has_errors + @gtfs_validator
@validators_with_has_errors_names = @validators_with_has_errors |> Enum.map(& &1.validator_name()
@gtfs_validator_name = @gtfs_validator.validator_name()
```

2023-11-24 13:23 UTC, vdegove commented on apps/transport/lib/jobs/dataset_quality_score.ex
> +      when validator in @validators_with_has_errors do
Ça me paraît correct, même si un peu plus lourd ça auto-documente et rajoute un peu de contrainte.

2023-11-24 13:25 UTC, thbar commented on apps/transport/lib/jobs/dataset_quality_score.ex
> +                              )
Les attributs d'un module ne sont pas accessibles à l'extérieur du module, mais on peut créer une méthode pour y accéder, auquel cas on peut faire des choses de ce type là (enfin c'est une stratégie disponible en tout cas, qu'on a utilisé à différents endroits).

2023-11-24 13:40 UTC, AntoineAugusti commented on apps/transport/lib/jobs/dataset_quality_score.ex
> +                              )
@vdegove Tu as raison, c'est bien plus propre en découpant. Fait dans https://github.com/etalab/transport-site/pull/3622/commits/e38673aa1e3c0262dbdac68d0c162289819258af

2023-11-24 13:41 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/templates/dataset/_dataset_scores.html.heex
`mix format` semble supprimer un non breaking space, je suis repassé sur un caractère espace 🤔 

Pas grave c'est uniquement pour les admins

2023-11-24 14:17 UTC, vdegove approved these changes

2023-11-24 14:23 UTC, merged