Mise à jour du contenu des notifications
etalab/transport-site pull request #3624
Opened 2023-11-24 09:56 UTC by AntoineAugusti

Fixes #3567

2023-11-28 14:46 UTC, vdegove requested changes

2023-11-28 14:46 UTC, vdegove commented on apps/transport/lib/transport_web/templates/email/expiration_producer.html.md
> +Afin de garantir une continuité dans l’utilisation de vos données, nous vous encourageons à anticiper les futures mises à jour au moins 7 jours avant la date d’expiration.
Il y a quelque chose que je ne trouve pas super actionnable car pas assez explicite concernant l’overlap de dates couvertes par une version d’une ressource et la suivante, et le moment où il faut les remplacer.

En gros, supposons qu’on a un JDD qui contient une resource GTFS avec des horaires courant du 1er janvier au 30 juin.

Si je comprends bien les instructions du PAN, le producteur de la donnée doit remplacer la resource actuelle avant le 23 juin (dans cet exemple) pour la version suivante. Mais du coup :
- Soit il publie disons le 20 juin une resource courant du 1er juillet au 31 décembre, et dans ce cas là, pendant quelques jours, il y a une resource en ligne qui ne couvre pas les dix prochain jours. Pas top.
- Soit il publie une nouvelle resource, pour avoir en même temps les deux périodes en lignes sur différents fichiers, du 1er janvier au 30 juin et du 1er juillet au 31 décembre, mais ça contrevient à nos instructions.
- Soit (et j’imagine que c’est la bonne pratique) il faut créer des resources qui commencent avant la date de péremption de la resource déjà en ligne, donc uploader le 20 juin une resource qui va (disons) du 1er juin au 31 décembre, **et donc créer un overlap des durées de validité des resources.**

Mais si c’est le cas, il faut mentionner cet overlap.

Aussi, le contenu du mail est distinct de ce qui est dit dans la FAQ. Dans la FAQ, on dit : si vous publiez plus de 7 jours avant, on vous conseille de créer une nouvelle resource (voir ici https://doc.transport.data.gouv.fr/administration-des-donnees/procedures-de-publication/mettre-a-jour-des-donnees#mettre-a-jour-ou-publier-une-nouvelle-ressource). Dans ce mail, on dit d’anticiper au moins avec 7 jours, mais de remplacer la resource. Il faudrait que les deux instructions soient alignées.

2023-11-28 14:46 UTC, vdegove commented on apps/transport/lib/transport/data_checker.ex
> +    "Jeu de données arrivant à expiration"
Il y a en parrallèle l’utilsation de l’expression « expiré / arrivant à expiration » et « périmé / périmant » un peu partout, y compris entre le sujet du mail et le contenu du même mail. Je serais en faveur d’utiliser soit l’un, soit l’autre (sauf si il y a une différence de sens entre la notion d’expiration et de péremption que je n’ai pas saisie).

2023-11-28 14:47 UTC, vdegove commented
J’ai fait des commentaires, après c’est plus pour @ChristinaLaumond et @cyrilmorin que pour @AntoineAugusti.

2023-11-30 10:25 UTC, AntoineAugusti commented on apps/transport/lib/transport/data_checker.ex
>    def gtfs_datasets_expiring_on(%Date{} = date) do
La modification est ici, permettre de pouvoir sortir dataset + ressources GTFS qui périment à une date donnée.

Auparavant on avait que le dataset.

2023-11-30 10:25 UTC, AntoineAugusti commented on apps/transport/test/transport/data_checker_test.exs
Pas mal d'adaptation de tests dans ce fichier ont été nécessaires pour s'adapter au nouveau type de retour sur `gtfs_datasets_expiring_on` : `{DB.Dataset.t(), [DB.Resource.t()]}`

2023-12-01 16:29 UTC, vdegove commented on apps/transport/lib/transport_web/templates/email/expiration_producer.html.md
> +Afin de garantir une continuité dans l’utilisation de vos données, nous vous encourageons à anticiper les futures mises à jour au moins 7 jours avant la date d’expiration.
Avant de valider la PR, j’aimerais bien @ChristinaLaumond avoir ton avis sur cette incohérence entre les instructions données ici et celles de la FAQ, et quelle version est la bonne. Si je résume :
- Ici on dit que il faut _toujours_ remplacer la resource d’origine, et d’ailleurs le faire au moins 7 jours avant
- Sur la FAQ on dit que si on remplace au moins 7 jours avant, ce qui est conseillé, il faut créer une nouvelle resource plutôt que remplacer l’existante
- On conseille dans ces instructions mails de s’y prendre en avance (logique) et de remplacer plutôt que créer une nouvelle, mais ça risque du coup de créer un trou si la nouvelle resource commence plus tard, et on a pas d’instructions spécifiques (constructions de resources avec des overlaps) pour contrer ça.

C’est le seul bloqueur (fort) pour moi, une fois que c’est expliqué on envoie :)

2023-12-05 12:44 UTC, thbar commented
@vdegove tu gardes la main pour reviewer cette PR ? Si besoin fais moi signe.

2023-12-05 13:03 UTC, AntoineAugusti commented
@thbar Oui tout à fait, il attend de clarifier ce point https://github.com/etalab/transport-site/pull/3624#discussion_r1412334347

2023-12-07 09:06 UTC, vdegove commented on apps/transport/lib/transport_web/templates/email/expiration_producer.html.md
> +Afin de garantir une continuité dans l’utilisation de vos données, nous vous encourageons à anticiper les futures mises à jour au moins 7 jours avant la date d’expiration.
Super ! FAQ super claire. Merci d’avoir levé cette incohérence dans nos instructions.

2023-12-07 09:49 UTC, vdegove commented on apps/transport/lib/transport/data_checker.ex
>    def gtfs_datasets_expiring_on(%Date{} = date) do
C’est pratique le @spec pour le coup, on comprend bien la sortie, ça documente le code.

2023-12-07 09:50 UTC, vdegove approved these changes

2023-12-07 09:56 UTC, merged