Rajout de l’id transport.data.gouv à l’API /datasets
etalab/transport-site pull request #3748
Opened 2024-01-25 15:02 UTC by vdegove

Closes #3746

En fait, il y a deux manières de clore ce ticket :
- Soit changer l’API et l’output des points d’arrêt GTFS, pour référencer les datagouv_id des datasets et non leur id
- Soit changer l’API des datasets

J’ai plutôt opté pour la deuxième option : ça me semblait pas très logique d’avoir un champ id identique à datagouv_id, et qui ne corresponde pas à notre id interne. Ce choix là semblait aussi guidé par le point d’entrée `/api/datasets/{id}`, qui prenait un datagouv_id en paramètre. Du coup, comme sur la version web, j’ai opté pour accepter les deux : `/api/datasets/{id}` va désormais donner le même contenu que `/api/datasets/{datagouv_id}`.

2024-01-25 15:07 UTC, vdegove commented
Ouvert à débat, je ne savais pas trop dans quel sens régler ça, soit dans l’API GTFS, soit dans dataset, et si il fallait changer le comportement de l’endpoint /datasets/{id} ou pas.

En fait, je ne sais pas trop sur quel pied danser avec les identifiants uniques externes (exemple : datagouv_id, codes INSEE divers…) et internes : faut-il éviter d’exposer les identifiants Ecto ? Est-ce qu’en interne, dans l’application, on utilise les identifants externes pour identifier des entrées, par exemple pour des foreign_keys (je l’ai fait sur les objets géographiques avec les codes INSEE, par exemple) ?

2024-01-25 15:37 UTC, vdegove commented on apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
> +      "id" => dataset.id,
Ok, tu peux détailler pourquoi ? Ça serait dans le cas où des gens en externe aient stocké cet id et s’appuient dessus ? (Remarque : datagouv_id est toujours présent dans le champ dédié, en fait jusque là il était en double.) Et même avec le changement du comportement de l’endpoint pour un dataset donné, c’est pas acceptable ?

Du coup, vaut mieux changer l’export GTFS et l’API GTFS ?

2024-01-25 15:53 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
> +      "id" => dataset.id,
`id` est une clé importante dans la réponse de notre API, il est probable que des personnes aient du code qui utilise cette valeur pour la stocker/la comparer avec d'autres systèmes. En modifiant la valeur de retour on casse tout ça. Le type est par ailleurs différent (str/int).

2024-01-25 16:00 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
> +      "id" => dataset.id,
> Du coup, vaut mieux changer l’export GTFS et l’API GTFS ?

on _pourrait_ s'en sortir en acceptant dans l'API `id` ou `datagouv_id` dans l'URL mais on n'expose pas notre identifiant de `DB.Dataset` dans l'API actuellement alors qu'on le fait dans l'export GTFS mis en open data.

Pas sûr de la meilleure manière de réconcilier ça. On verra ce que @thbar en pense.

2024-01-25 16:31 UTC, vdegove commented on apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
> +      "id" => dataset.id,
> on pourrait s'en sortir en acceptant dans l'API id ou datagouv_id dans l'URL

C’est ce que fait cette PR, mais la description était peut-être trop brouillonne (ou alors j’ai pas compris ton message).

2024-01-25 16:45 UTC, AntoineAugusti commented on apps/transport/lib/transport_web/api/controllers/datasets_controller.ex
> +      "id" => dataset.id,
Yep, j'ai bien vu ça, mais sans changer le sens du champ `id` dans la réponse.

2024-01-26 08:09 UTC, thbar requested changes
Je suis du même avis que @AntoineAugusti : changer l'output de l'API n'est pas une bonne idée à ce stade et de cette façon.

En effet depuis:
- https://github.com/etalab/transport-site/pull/3243

On a pu mesurer son usage, qui tourne actuellement aux environs de 120k requêtes par mois.

Autant avant on aurait pu se dire YOLO on y va break things and ship fast, autant là on sait qu'il y a des pipelines de données automatisés en face, et que ça va créer de la casse, et on ne le souhaite pas.

Il faudra clairement une API v2 à un moment pour remettre tout à plat (sûrement en side-by-side pour laisser le temps aux gens de migrer), mais là on préfère ne rien casser, ou éviter le plus possible (on aurait un message avec un deprecation warning en avance de phase, why not par exemple).

> En fait, il y a deux manières de clore ce ticket :
> - Soit changer l’API des datasets
> - Soit changer l’API et l’output des points d’arrêt GTFS, pour référencer les datagouv_id des datasets et non leur id

Donc la solution 1 a été mise de côté par vote ici :smile: 

Je pense qu'on peut opter pour une solution 2 modifiée, où tu "ajoutes" les ids des datasets en plus de l'id technique.

Il est plus facile de changer cet export qui est réputé expérimental, que de toucher à l'API.

Donc voilà ce que je te propose, est-ce qu'un ajout de champ répondra suffisamment bien à l'utilisateur ? (je n'ai pas regardé le détail depuis la dernière fois).

2024-01-26 09:41 UTC, vdegove commented
Je comprends, merci pour votre vigilance :) Bon, du coup, je ferme cette branche, j’en crée une autre.

2024-01-26 09:41 UTC, closed without merging

2024-01-26 12:00 UTC, thbar commented
> Je comprends, merci pour votre vigilance :) Bon, du coup, je ferme cette branche, j’en crée une autre.

Ça marche, merci pour la discussion et bon courage pour la branche suivante, c'est plus facile effectivement !